/**
 * Maps zenless.tools image basenames (without extension) to codebase character names.
 * @see https://zenless.tools/leveling-calculator
 */
export const ZENLESS_TO_CHARACTER_NAME: Record<string, string> = {
  alexandrina: "alexandrina",
  alice_thymefield: "alice",
  anby_demara: "anby",
  anton_ivanov: "anton",
  aria: "aria",
  asaba_harumasa: "harumasa",
  astra_yao_v2: "astra-yao",
  astra_yao: "astra-yao",
  banyue_v2: "banyue",
  banyue: "banyue",
  ben_bigger: "ben",
  billy_kid: "billy",
  burnice: "burnice",
  caesar_king: "caesar",
  cissia: "cissia",
  corin_wickes: "corin",
  dialyn: "dialyn",
  ellen_joe: "ellen",
  evelyn_v2: "evelyn",
  evelyn: "evelyn",
  grace_howard: "grace",
  hoshimi_miyabi: "miyabi",
  hugo: "hugo",
  jane_doe_v2: "jane",
  jane_doe: "jane",
  ju_fufu: "jufufu",
  koleda_belobog: "koleda",
  komano_manato: "komano",
  lighter: "lighter",
  lucia_v2: "lucia",
  lucia: "lucia",
  lucy: "lucy",
  nangong_yu: "nangong_yu",
  nekomiya_mana: "nekomiya",
  nicole_demara: "nicole",
  norma: "norma",
  orphie: "orphie",
  pan_yinhu: "pan yinhu",
  piper_wheel: "piper",
  promeia: "promeia",
  pulchra_v2: "pulchra",
  pulchra: "pulchra",
  pyrois: "pyrois",
  qingyi: "qingyi",
  remielle: "remielle",
  seed: "seed",
  seth_lowell: "seth",
  sigrid: "sigrid",
  // Silver Soldier Anby on zenless.tools → sanby in this app
  soldier_0: "sanby",
  soldier_11_v2: "soldier-11",
  soldier_11: "soldier-11",
  soukaku: "soukaku",
  starlight_billy: "starlight_billy",
  sunna: "sunna",
  trigger_v2: "trigger",
  trigger: "trigger",
  tsukishiro_yanagi: "yanagi",
  ukinami_yuzuha: "yuzuha",
  velina: "velina",
  vivian: "vivian",
  von_lycaon: "lycaon",
  ye_shunguang: "ye_shunguang",
  yidhari: "yidhari",
  yixuan: "yixuan",
  zhao: "zhao",
  zhu_yuan: "zhu-yuan",
};

/** Characters in our database that are not on zenless.tools (kept as-is). */
export const LOCAL_ONLY_CHARACTERS = new Set(["isolde"]);
