import { Playlist } from "@/types/playlist.type";

export const Albums: Record<string, Omit<Playlist, "tracks">> = {
  "astra-yao": {
    playlist_name: "Astra Yao",
    playlist_cover: "/characters/astra-yao.png",
    playlist_id: "astra-yao",
    playlist_type: "character",
  },
  isolde: {
    playlist_name: "Isolde",
    playlist_cover: "/characters/isolde.png",
    playlist_id: "isolde",
    playlist_type: "character",
  },
  "eous-anthems": {
    playlist_name: "Eous Anthems",
    playlist_cover: "/covers/eous-anthems.jpg",
    playlist_id: "eous-anthems",
    playlist_type: "jukebox",
  },
  "astra-nomical--moment": {
    playlist_name: "Astra-Nomical Moment",
    playlist_cover: "/covers/astra-nomical--moment.jpg",
    playlist_id: "astra-nomical--moment",
    playlist_type: "jukebox",
  },
  "1.4": {
    playlist_name: "A Storm of Falling Stars",
    playlist_cover: "/covers/1.4.jpg",
    playlist_id: "1.4",
    playlist_type: "jukebox",
  },
  "come-alive": {
    playlist_name: "Come Alive",
    playlist_cover: "/covers/come-alive.jpg",
    playlist_id: "come-alive",
    playlist_type: "jukebox",
  },
  "casual-savior": {
    playlist_name: "Casual Savior",
    playlist_cover: "/covers/casual-savior.jpg",
    playlist_id: "casual-savior",
    playlist_type: "jukebox",
  },
  "daily-loop": {
    playlist_name: "Daily Loop",
    playlist_cover: "/covers/daily-loop.jpg",
    playlist_id: "daily-loop",
    playlist_type: "jukebox",
  },
  "shared-earbuds": {
    playlist_name: "Shared Earbuds",
    playlist_cover: "/covers/shared-earbuds.jpg",
    playlist_id: "shared-earbuds",
    playlist_type: "jukebox",
  },
  "random-play": {
    playlist_name: "Random Play",
    playlist_cover: "/covers/random-play.jpg",
    playlist_id: "random-play",
    playlist_type: "jukebox",
  },
  "virtual-revenge": {
    playlist_name: "Virtual Revenge",
    playlist_cover: "/covers/virtual-revenge.jpeg",
    playlist_id: "virtual-revenge",
    playlist_type: "jukebox",
  },
  ellen: {
    playlist_name: "Ellen Joe",
    playlist_cover: "/characters/ellen.png",
    playlist_id: "ellen-joe",
    playlist_type: "character",
  },
  burnice: {
    playlist_name: "Burnice",
    playlist_cover: "/characters/burnice.png",
    playlist_id: "burnice",
    playlist_type: "character",
  },
  anby: {
    playlist_name: "Anby",
    playlist_cover: "/characters/anby.png",
    playlist_id: "anby",
    playlist_type: "character",
  },
  caesar: {
    playlist_name: "Caesar",
    playlist_cover: "/characters/caesar.png",
    playlist_id: "caesar",
    playlist_type: "character",
  },
  "zhu-yuan": {
    playlist_name: "Zhu Yuan",
    playlist_cover: "/characters/zhu-yuan.png",
    playlist_id: "zhu-yuan",
    playlist_type: "character",
  },
  jane: {
    playlist_name: "Jane",
    playlist_cover: "/characters/jane.png",
    playlist_id: "jane-doe",
    playlist_type: "character",
  },
  koleda: {
    playlist_name: "Koleda",
    playlist_cover: "/characters/koleda.png",
    playlist_id: "koleda",
    playlist_type: "character",
  },
  lighter: {
    playlist_name: "Lighter",
    playlist_cover: "/characters/lighter.png",
    playlist_id: "lighter",
    playlist_type: "character",
  },
  nicole: {
    playlist_name: "Nicole",
    playlist_cover: "/characters/nicole.png",
    playlist_id: "nicole",
    playlist_type: "character",
  },
  harumasa: {
    playlist_name: "Harumasa",
    playlist_cover: "/characters/harumasa.png",
    playlist_id: "harumasa",
    playlist_type: "character",
  },
  miyabi: {
    playlist_name: "Miyabi",
    playlist_cover: "/characters/miyabi.png",
    playlist_id: "miyabi",
    playlist_type: "character",
  },
  lycaon: {
    playlist_name: "Lycaon",
    playlist_cover: "/characters/lycaon.png",
    playlist_id: "lycaon",
    playlist_type: "character",
  },
  nekomata: {
    playlist_name: "Nekomata",
    playlist_cover: "/characters/nekomiya.png",
    playlist_id: "nekomata",
    playlist_type: "character",
  },
  qingyi: {
    playlist_name: "Qingyi",
    playlist_cover: "/characters/qingyi.png",
    playlist_id: "qingyi",
    playlist_type: "character",
  },
  yanagi: {
    playlist_name: "Yanagi",
    playlist_cover: "/characters/yanagi.png",
    playlist_id: "yanagi",
    playlist_type: "character",
  },
  loading: {
    playlist_name: "Loading",
    playlist_cover: "/covers/loading.jpg",
    playlist_id: "loading",
    playlist_type: "jukebox",
  },
  "roaming-the-ether": {
    playlist_name: "Roaming the Ether",
    playlist_cover: "/covers/roaming-the-ether.jpg",
    playlist_id: "roaming-the-ether",
    playlist_type: "jukebox",
  },
  "overlords-feast": {
    playlist_name: "Overlords Feast",
    playlist_cover: "/covers/overlords-feast.jpg",
    playlist_id: "overlords-feast",
    playlist_type: "jukebox",
  },
  "first-class-customer-service": {
    playlist_name: "First Class Customer Service",
    playlist_cover: "/covers/first-class-customer-service.jpg",
    playlist_id: "first-class-customer-service",
    playlist_type: "jukebox",
  },
  "daily-life-of-a-pubsec-officer": {
    playlist_name: "Daily Life of a PubSec Officer",
    playlist_cover: "/covers/daily-life-of-a-pubsec-officer.jpg",
    playlist_id: "daily-life-of-a-pubsec-officer",
    playlist_type: "jukebox",
  },
  "camelia-golden-week": {
    playlist_name: "Camelina Golden Week",
    playlist_cover: "/covers/camelia-golden-week.jpg",
    playlist_id: "camelia-golden-week",
    playlist_type: "jukebox",
  },
  "en-nah-assistant-program": {
    playlist_name: "En Nah' Assistant Program",
    playlist_cover: "/covers/en-nah-assistant-program.jpg",
    playlist_id: "en-nah-assistant-program",
    playlist_type: "jukebox",
  },
  "when-sandwiches-come-a-knockin": {
    playlist_name: "When Sandwiches Come a Knockin'",
    playlist_cover: "/covers/when-sandwiches-come-a-knockin.jpg",
    playlist_id: "when-sandwiches-come-a-knockin",
    playlist_type: "jukebox",
  },
  "bangboo-vs-ethereal": {
    playlist_name: "Bangboo vs Ethereal",
    playlist_cover: "/covers/bangboo-vs-ethereal.jpg",
    playlist_id: "bangboo-vs-ethereal",
    playlist_type: "jukebox",
  },
  "unreleased-songs": {
    playlist_name: "Unreleased Songs",
    playlist_cover: "/covers/unreleased-songs.jpg",
    playlist_id: "unreleased-songs",
    playlist_type: "jukebox",
  },
  billy: {
    playlist_name: "Billy",
    playlist_cover: "/characters/billy.png",
    playlist_id: "billy",
    playlist_type: "character",
  },
  grace: {
    playlist_name: "Grace",
    playlist_cover: "/characters/grace.png",
    playlist_id: "grace",
    playlist_type: "character",
  },
  sanby: {
    playlist_name: "Sanby",
    playlist_cover: "/characters/sanby.png",
    playlist_id: "sanby",
    playlist_type: "character",
  },
  trigger: {
    playlist_name: "Trigger",
    playlist_cover: "/characters/trigger.png",
    playlist_id: "trigger",
    playlist_type: "character",
  },
  vivian: {
    playlist_name: "Vivian",
    playlist_cover: "/characters/vivian.png",
    playlist_id: "vivian",
    playlist_type: "character",
  },
  evelyn: {
    playlist_name: "Evelyn",
    playlist_cover: "/characters/evelyn.png",
    playlist_id: "evelyn",
    playlist_type: "character",
  },
  pulchra: {
    playlist_name: "Pulchra",
    playlist_cover: "/characters/pulchra.png",
    playlist_id: "pulchra",
    playlist_type: "character",
  },
  hugo: {
    playlist_name: "Hugo",
    playlist_cover: "/characters/hugo.png",
    playlist_id: "hugo",
    playlist_type: "character",
  },
  seed: {
    playlist_name: "Seed",
    playlist_cover: "/characters/seed.webp",
    playlist_id: "seed",
    playlist_type: "character",
  },
  yidhari: {
    playlist_name: "Yidhari",
    playlist_cover: "/characters/yidhari.webp",
    playlist_id: "yidhari",
    playlist_type: "character",
  },
  orphie: {
    playlist_name: "Orphie",
    playlist_cover: "/characters/orphie.webp",
    playlist_id: "orphie",
    playlist_type: "character",
  },
  lucia: {
    playlist_name: "Lucia",
    playlist_cover: "/characters/lucia.webp",
    playlist_id: "lucia",
    playlist_type: "character",
  },
  banyue: {
    playlist_name: "Banyue",
    playlist_cover: "/characters/banyue.webp",
    playlist_id: "banyue",
    playlist_type: "character",
  },
  dialyn: {
    playlist_name: "Dialyn",
    playlist_cover: "/characters/dialyn.webp",
    playlist_id: "dialyn",
    playlist_type: "character",
  },
  yixuan: {
    playlist_name: "Yixuan",
    playlist_cover: "/characters/yixuan.webp",
    playlist_id: "yixuan",
    playlist_type: "character",
  },
  jufufu: {
    playlist_name: "Ju Fufu",
    playlist_cover: "/characters/ju_fufu.webp",
    playlist_id: "jufufu",
    playlist_type: "character",
  },
  yuzuha: {
    playlist_name: "Yuzuha",
    playlist_cover: "/characters/ukinami_yuzuha.webp",
    playlist_id: "yuzuha",
    playlist_type: "character",
  },
  "1.6": {
    playlist_name: "Among the Forgotten Ruins",
    playlist_cover: "/covers/1.6.jpg",
    playlist_id: "1.6",
    playlist_type: "jukebox",
  },
  "1.7": {
    playlist_name: "Bury Your Tears With the Past",
    playlist_cover: "/covers/1.7.jpg",
    playlist_id: "1.7",
    playlist_type: "jukebox",
  },
  "2.0": {
    playlist_name: "Where Clouds Embrace the Dawn",
    playlist_cover: "/covers/2.0.jpg",
    playlist_id: "2.0",
    playlist_type: "jukebox",
  },
  "2.1": {
    playlist_name: "The Impending Crash of Waves",
    playlist_cover: "/covers/2.1.jpeg",
    playlist_id: "2.1",
    playlist_type: "jukebox",
  },
  "2.2": {
    playlist_name: "Do Not Go Gentle Into That Good Night",
    playlist_cover: "/covers/2.2.jpg",
    playlist_id: "2.2",
    playlist_type: "jukebox",
  },
  "2.3": {
    playlist_name: "Memories of Dreams Bygone",
    playlist_cover: "/covers/2.3.jpeg",
    playlist_id: "2.3",
    playlist_type: "jukebox",
  },
  "2.4": {
    playlist_name: "On the Precipice of the Abyss",
    playlist_cover: "/covers/2.4.jpeg",
    playlist_id: "2.4",
    playlist_type: "jukebox",
  },
  "2.5": {
    playlist_name: "To Be Fuel for the Night",
    playlist_cover: "/covers/2.5.jpg",
    playlist_id: "2.5",
    playlist_type: "jukebox",
  },
  "2.6": {
    playlist_name: "Encore for an Old Dream",
    playlist_cover: "/covers/2.6.jpg",
    playlist_id: "2.6",
    playlist_type: "jukebox",
  },
  "2.7": {
    playlist_name: "Champions Never Fall to the Past",
    playlist_cover: "/covers/2.7.jpg",
    playlist_id: "2.7",
    playlist_type: "jukebox",
  },
  "2.8": {
    playlist_name: "New: Eridan Sunset",
    playlist_cover: "/covers/2.8.jpg",
    playlist_id: "2.8",
    playlist_type: "jukebox",
  },
  "3.0": {
    playlist_name: "A Sleepwalker's Confession",
    playlist_cover: "/covers/3.0.jpg",
    playlist_id: "3.0",
    playlist_type: "jukebox",
  },
  zhao: {
    playlist_name: "Zhao",
    playlist_cover: "/characters/zhao.webp",
    playlist_id: "zhao",
    playlist_type: "character",
  },
  "ye-shunguang": {
    playlist_name: "Ye Shunguang",
    playlist_cover: "/characters/ye_shunguang.webp",
    playlist_id: "ye-shunguang",
    playlist_type: "character",
  },
  aria: {
    playlist_name: "Aria",
    playlist_cover: "/characters/aria.webp",
    playlist_id: "aria",
    playlist_type: "character",
  },
  sunna: {
    playlist_name: "Sunna",
    playlist_cover: "/characters/sunna.webp",
    playlist_id: "sunna",
    playlist_type: "character",
  },
  rina: {
    playlist_name: "Rina",
    playlist_cover: "/characters/alexandrina.png",
    playlist_id: "rina",
    playlist_type: "character",
  },
  "nangong-yu": {
    playlist_name: "Nangong Yu",
    playlist_cover: "/characters/nangong_yu.webp",
    playlist_id: "nangong-yu",
    playlist_type: "character",
  },
  cissia: {
    playlist_name: "Cissia",
    playlist_cover: "/characters/cissia.webp",
    playlist_id: "cissia",
    playlist_type: "character",
  },
  promeia: {
    playlist_name: "Promeia",
    playlist_cover: "/characters/promeia.webp",
    playlist_id: "promeia",
    playlist_type: "character",
  },
  "starlight-billy": {
    playlist_name: "Starlight Billy",
    playlist_cover: "/characters/starlight_billy.webp",
    playlist_id: "starlight-billy",
    playlist_type: "character",
  },
  remielle: {
    playlist_name: "Remielle",
    playlist_cover: "/characters/remielle.webp",
    playlist_id: "remielle",
    playlist_type: "character",
  },
  norma: {
    playlist_name: "Norma",
    playlist_cover: "/characters/norma.webp",
    playlist_id: "norma",
    playlist_type: "character",
  },
  "dreamland-fest": {
    playlist_name: "Dreamland Fest",
    playlist_cover: "/covers/dreamland-fest.jpg",
    playlist_id: "dreamland-fest",
    playlist_type: "jukebox",
  },
};
