import { Track } from "@/types/track.type";
import { Albums } from "../albums";
import { Artists } from "../artists";
import { YixuanTracks } from "./yixuan";
import { JufufuTracks } from "./jufufu";

export const Album20Tracks: Track[] = [
  {
    title: "Purge Corruption, Restore Clarity Theme",
    title_id: "purge-corruption-restore-clarity-theme",
    source: "/musics/2.0--purge-corruption-restore-clarity-theme.mp3",
    duration: 89,
    created_at: new Date("2025-07-29T18:00:49Z"),
    ...Artists["2.0"],
  },
  {
    title: "Phantom Dreams Theme",
    title_id: "phantom-dreams-theme",
    source: "/musics/2.0--phantom-dreams-theme.mp3",
    duration: 44,
    created_at: new Date("2025-07-29T17:40:00Z"),
    ...Artists["2.0"],
  },
  {
    title: "New Visitors at Suibian Temple Theme",
    title_id: "new-visitors-at-suibian-temple-theme",
    source: "/musics/2.0--new-visitors-at-suibian-temple-theme.mp3",
    duration: 42,
    created_at: new Date("2025-07-29T17:20:00Z"),
    ...Artists["2.0"],
  },
  {
    title: "Stargazing at Night Theme",
    title_id: "stargazing-at-night-theme",
    source: "/musics/2.0--stargazing-at-night-theme.mp3",
    duration: 57,
    created_at: new Date("2025-07-29T17:00:23Z"),
    ...Artists["2.0"],
  },
  {
    title: "An Empty House Theme",
    title_id: "an-empty-house-theme",
    source: "/musics/2.0--an-empty-house-theme.mp3",
    duration: 198,
    created_at: new Date("2025-06-10T19:01:01Z"),
    ...Artists["2.0"],
  },
  {
    title: "The Exaltists Theme",
    title_id: "the-exaltists-theme",
    source: "/musics/2.0--the-exaltists-theme.mp3",
    duration: 137,
    created_at: new Date("2025-06-10T18:30:55Z"),
    ...Artists["2.0"],
  },
  {
    title: "Ether Tuning Theme",
    title_id: "ether-tuning-theme",
    source: "/musics/2.0--ether-tuning-theme.mp3",
    duration: 111,
    created_at: new Date("2025-06-10T18:00:32Z"),
    ...Artists["2.0"],
  },
  {
    title: "Golden Proxy Awards Theme (Best Proxy Award)",
    title_id: "golden-proxy-awards-theme-best-proxy-award",
    source: "/musics/2.0--golden-proxy-awards-theme-best-proxy-award.mp3",
    duration: 129,
    created_at: new Date("2025-06-10T17:30:09Z"),
    ...Artists["2.0"],
  },
  {
    title: "Golden Proxy Awards Theme",
    title_id: "golden-proxy-awards-theme",
    source: "/musics/2.0--golden-proxy-awards-theme.mp3",
    duration: 194,
    created_at: new Date("2025-06-10T17:00:41Z"),
    ...Artists["2.0"],
  },
  {
    title: "Failume Heights Theme - Years of Stars (Weekend - Night)",
    title_id: "failume-heights-theme-years-of-stars-weekend-night",
    source:
      "/musics/2.0--failume-heights-theme-years-of-stars-weekend-night.mp3",
    duration: 274,
    created_at: new Date("2025-06-09T18:30:52Z"),
    ...Artists["2.0"],
  },
  {
    title: "Failume Heights Theme - Afternoon Gossip (Weekend - Day)",
    title_id: "failume-heights-theme-afternoon-gossip-weekend-day",
    source:
      "/musics/2.0--failume-heights-theme-afternoon-gossip-weekend-day.mp3",
    duration: 249,
    created_at: new Date("2025-06-09T18:00:44Z"),
    ...Artists["2.0"],
  },
  {
    title: "Failume Heights Theme - Lightstream Alley (Weekday - Night)",
    title_id: "failume-heights-theme-lightstream-alley-weekday-night",
    source:
      "/musics/2.0--failume-heights-theme-lightstream-alley-weekday-night.mp3",
    duration: 269,
    created_at: new Date("2025-06-09T17:30:11Z"),
    ...Artists["2.0"],
  },
  {
    title: "Failume Heights Theme - Sunny Failume (Weekday - Day)",
    title_id: "failume-heights-theme-sunny-failume-weekday-day",
    source: "/musics/2.0--failume-heights-theme-sunny-failume-weekday-day.mp3",
    duration: 232,
    created_at: new Date("2025-06-09T17:00:48Z"),
    ...Artists["2.0"],
  },
  {
    title: "Gravity Cinema Theme",
    title_id: "gravity-cinema-theme",
    source: "/musics/2.0--gravity-cinema-theme.mp3",
    duration: 128,
    created_at: new Date("2025-06-09T09:30:03Z"),
    ...Artists["2.0"],
  },
  {
    title: "Gravitational Attraction Event Theme 2 (Movie Date)",
    title_id: "gravitational-attraction-event-theme-2-movie-date",
    source:
      "/musics/2.0--gravitational-attraction-event-theme-2-movie-date.mp3",
    duration: 168,
    created_at: new Date("2025-06-09T09:01:07Z"),
    ...Artists["2.0"],
  },
  {
    title: "Suibian Temple Theme 2",
    title_id: "suibian-temple-theme-2",
    source: "/musics/2.0--suibian-temple-theme-2.mp3",
    duration: 582,
    created_at: new Date("2025-06-09T07:00:09Z"),
    ...Artists["2.0"],
  },
  {
    title: "Gravitational Attraction Event Theme 1 (Movie Date)",
    title_id: "gravitational-attraction-event-theme-1-movie-date",
    source:
      "/musics/2.0--gravitational-attraction-event-theme-1-movie-date.mp3",
    duration: 228,
    created_at: new Date("2025-06-08T18:30:54Z"),
    ...Artists["2.0"],
  },
  {
    title: "Gravitational Attraction Event Theme 2 (Light & Shadow Exclusive)",
    title_id:
      "gravitational-attraction-event-theme-2-light-and-shadow-exclusive",
    source:
      "/musics/2.0--gravitational-attraction-event-theme-2-light-and-shadow-exclusive.mp3",
    duration: 182,
    created_at: new Date("2025-06-08T18:00:30Z"),
    ...Artists["2.0"],
  },
  {
    title: "Gravitational Attraction Event Theme 1 (Light & Shadow Exclusive)",
    title_id:
      "gravitational-attraction-event-theme-1-light-and-shadow-exclusive",
    source:
      "/musics/2.0--gravitational-attraction-event-theme-1-light-and-shadow-exclusive.mp3",
    duration: 182,
    created_at: new Date("2025-06-08T17:30:06Z"),
    ...Artists["2.0"],
  },
  {
    title: "Suibian Temple Theme 1",
    title_id: "suibian-temple-theme-1",
    source: "/musics/2.0--suibian-temple-theme-1.mp3",
    duration: 334,
    created_at: new Date("2025-06-08T17:01:12Z"),
    ...Artists["2.0"],
  },
  {
    title: "Devon Pawnshop Theme (Devon Emergency Relief)",
    title_id: "devon-pawnshop-theme-devon-emergency-relief",
    source: "/musics/2.0--devon-pawnshop-theme-devon-emergency-relief.mp3",
    duration: 213,
    created_at: new Date("2025-06-08T04:30:20Z"),
    ...Artists["2.0"],
  },
  {
    title: "Yum Cha Sin Shop Theme",
    title_id: "yum-cha-sin-shop-theme",
    source: "/musics/2.0--yum-cha-sin-shop-theme.mp3",
    duration: 243,
    created_at: new Date("2025-06-08T04:00:45Z"),
    ...Artists["2.0"],
  },
  {
    title: "Soul of Steel Event Battle Theme 2 (VS Hurcules)",
    title_id: "soul-of-steel-event-battle-theme-2-vs-hurcules",
    source: "/musics/2.0--soul-of-steel-event-battle-theme-2-vs-hurcules.mp3",
    duration: 159,
    created_at: new Date("2025-06-07T18:00:32Z"),
    ...Artists["2.0"],
  },
  {
    title: "Soul of Steel Event Battle Theme 1",
    title_id: "soul-of-steel-event-battle-theme-1",
    source: "/musics/2.0--soul-of-steel-event-battle-theme-1.mp3",
    duration: 181,
    created_at: new Date("2025-06-07T17:30:00Z"),
    ...Artists["2.0"],
  },
  {
    title: "Soul of Steel Event Menu Theme",
    title_id: "soul-of-steel-event-menu-theme",
    source: "/musics/2.0--soul-of-steel-event-menu-theme.mp3",
    duration: 121,
    created_at: new Date("2025-06-07T17:00:55Z"),
    ...Artists["2.0"],
  },
  {
    title: "Aerospace City Exploration Theme 3 (Lemnian Hollow)",
    title_id: "aerospace-city-exploration-theme-3-lemnian-hollow",
    source:
      "/musics/2.0--aerospace-city-exploration-theme-3-lemnian-hollow.mp3",
    duration: 242,
    created_at: new Date("2025-06-07T10:01:30Z"),
    ...Artists["2.0"],
  },
  {
    title: "Aerospace City Exploration Theme 2 (Lemnian Hollow)",
    title_id: "aerospace-city-exploration-theme-2-lemnian-hollow",
    source:
      "/musics/2.0--aerospace-city-exploration-theme-2-lemnian-hollow.mp3",
    duration: 191,
    created_at: new Date("2025-06-07T09:30:15Z"),
    ...Artists["2.0"],
  },
  {
    title: "Aerospace City Exploration Theme 1 (Lemnian Hollow)",
    title_id: "aerospace-city-exploration-theme-1-lemnian-hollow",
    source:
      "/musics/2.0--aerospace-city-exploration-theme-1-lemnian-hollow.mp3",
    duration: 212,
    created_at: new Date("2025-06-07T09:00:36Z"),
    ...Artists["2.0"],
  },
  {
    title: "Aerospace City Battle Theme 3 - Darkest Hour (Lemnian Hollow)",
    title_id: "aerospace-city-battle-theme-3-darkest-hour-lemnian-hollow",
    source:
      "/musics/2.0--aerospace-city-battle-theme-3-darkest-hour-lemnian-hollow.mp3",
    duration: 204,
    created_at: new Date("2025-06-07T07:00:01Z"),
    ...Artists["2.0"],
  },
  {
    title: "Aerospace City Battle Theme 2 (Lemnian Hollow)",
    title_id: "aerospace-city-battle-theme-2-lemnian-hollow",
    source: "/musics/2.0--aerospace-city-battle-theme-2-lemnian-hollow.mp3",
    duration: 182,
    created_at: new Date("2025-06-07T06:30:19Z"),
    ...Artists["2.0"],
  },
  {
    title: "Aerospace City Battle Theme 1 (Lemnian Hollow)",
    title_id: "aerospace-city-battle-theme-1-lemnian-hollow",
    source: "/musics/2.0--aerospace-city-battle-theme-1-lemnian-hollow.mp3",
    duration: 182,
    created_at: new Date("2025-06-07T06:00:08Z"),
    ...Artists["2.0"],
  },
  {
    title: "Aerospace City Theme 3 (Lemnian Hollow)",
    title_id: "aerospace-city-theme-3-lemnian-hollow",
    source: "/musics/2.0--aerospace-city-theme-3-lemnian-hollow.mp3",
    duration: 213,
    created_at: new Date("2025-06-07T04:30:26Z"),
    ...Artists["2.0"],
  },
  {
    title: "Aerospace City Theme 2 (Lemnian Hollow)",
    title_id: "aerospace-city-theme-2-lemnian-hollow",
    source: "/musics/2.0--aerospace-city-theme-2-lemnian-hollow.mp3",
    duration: 189,
    created_at: new Date("2025-06-07T04:00:56Z"),
    ...Artists["2.0"],
  },
  {
    title: "Aerospace City Theme 1 (Lemnian Hollow)",
    title_id: "aerospace-city-theme-1-lemnian-hollow",
    source: "/musics/2.0--aerospace-city-theme-1-lemnian-hollow.mp3",
    duration: 198,
    created_at: new Date("2025-06-06T13:30:37Z"),
    ...Artists["2.0"],
  },
  {
    title: '"Mevorakh" - Miasma Priest Boss Theme (Overseer - Mevorakh)',
    title_id: "mevorakh-miasma-priest-boss-theme-overseer-mevorakh",
    source:
      "/musics/2.0--mevorakh-miasma-priest-boss-theme-overseer-mevorakh.mp3",
    duration: 290,
    created_at: new Date("2025-06-06T10:30:37Z"),
    ...Artists["2.0"],
  },
  {
    title: "Miasma Priest Boss Theme (Overseer - Mevorakh) Story Ver.",
    title_id: "miasma-priest-boss-theme-overseer-mevorakh-story-ver",
    source:
      "/musics/2.0--miasma-priest-boss-theme-overseer-mevorakh-story-ver.mp3",
    duration: 378,
    created_at: new Date("2025-06-06T09:17:00Z"),
    ...Artists["2.0"],
  },
  {
    title: "Where Clouds Embrace the Dawn Theme (Teaser Trailer)",
    title_id: "where-clouds-embrace-the-dawn-theme-teaser-trailer",
    source:
      "/musics/2.0--where-clouds-embrace-the-dawn-theme-teaser-trailer.mp3",
    duration: 160,
    created_at: new Date("2025-06-06T02:10:01Z"),
    ...Artists["2.0"],
  },
  {
    title: "Where Clouds Embrace the Dawn Theme (Event Preview)",
    title_id: "where-clouds-embrace-the-dawn-theme-event-preview",
    source:
      "/musics/2.0--where-clouds-embrace-the-dawn-theme-event-preview.mp3",
    duration: 192,
    created_at: new Date("2025-05-23T17:00:41Z"),
    ...Artists["2.0"],
  },
  {
    title: "2.0 Web Event Theme (Next Stop: Waifei Peninsula!)",
    title_id: "2-0-web-event-theme-next-stop-waifei-peninsula",
    source: "/musics/2.0--2-0-web-event-theme-next-stop-waifei-peninsula.mp3",
    duration: 249,
    created_at: new Date("2025-05-23T13:30:17Z"),
    ...Artists["2.0"],
  },
  ...YixuanTracks.filter((track) => track.artist_id === "2.0"),
  ...JufufuTracks,
].map((track) => ({
  ...track,
  ...Albums["2.0"],
}));
