import { Track } from "@/types/track.type";
import { Albums } from "../albums";
import { Artists } from "../artists";
import { YuzuhaTracks } from "./yuzuha";

export const Album21Tracks: Track[] = [
  {
    title: "Aqua Blaster Ride Minigame - Archipelago Shoot",
    title_id: "aqua-blaster-ride-minigame-archipelago-shoot",
    source: "/musics/2.1--aqua-blaster-ride-minigame-archipelago-shoot.mp3",
    duration: 182,
    created_at: new Date("2025-12-16"),
    ...Artists["2.1"],
  },
  {
    title: "Battle Trials - Glory - Endless Tower Theme (HQ Ver.)",
    title_id: "battle-trials-glory-endless-tower-theme-hq-ver",
    source: "/musics/2.1--battle-trials-glory-endless-tower-theme-hq-ver.mp3",
    duration: 395,
    created_at: new Date("2025-12-16"),
    ...Artists["2.1"],
  },
  {
    title: "Battle Trials - Glory - Endless Tower Theme",
    title_id: "battle-trials-glory-endless-tower-theme",
    source: "/musics/2.1--battle-trials-glory-endless-tower-theme.mp3",
    duration: 393,
    created_at: new Date("2025-12-16"),
    ...Artists["2.1"],
  },
  {
    title: "En-Nah Chess Legend Event Theme 1",
    title_id: "en-nah-chess-legend-event-theme-1",
    source: "/musics/2.1--en-nah-chess-legend-event-theme-1.mp3",
    duration: 168,
    created_at: new Date("2025-12-16"),
    ...Artists["2.1"],
  },
  {
    title: "En-Nah Chess Legend Event Theme 2",
    title_id: "en-nah-chess-legend-event-theme-2",
    source: "/musics/2.1--en-nah-chess-legend-event-theme-2.mp3",
    duration: 272,
    created_at: new Date("2025-12-16"),
    ...Artists["2.1"],
  },
  {
    title: "En-Nah Chess Legend Event Main Menu Theme",
    title_id: "en-nah-chess-legend-event-main-menu-theme",
    source: "/musics/2.1--en-nah-chess-legend-event-theme-main-menu.mp3",
    duration: 172,
    created_at: new Date("2025-12-16"),
    ...Artists["2.1"],
  },
  {
    title: "Endless Tower - Glory Theme (Instrumental Ver.)",
    title_id: "endless-tower-glory-theme-instrumental-ver",
    source: "/musics/2.1--endless-tower-glory-theme-instrumental-ver.mp3",
    duration: 208,
    created_at: new Date("2025-12-16"),
    ...Artists["2.1"],
  },
  {
    title: "Fantasy Music Festival - Tales of Midsummer Dreams Ending Theme",
    title_id: "fantasy-music-festival-tales-of-midsummer-dreams-ending-theme",
    source:
      "/musics/2.1--fantasy-music-festival-tales-of-midsummer-dreams-ending-theme.mp3",
    duration: 45,
    created_at: new Date("2025-12-16"),
    ...Artists["2.1"],
  },
  {
    title: "Fantasy Resort Theme - Midsummer Fantasy Days",
    title_id: "fantasy-resort-theme-midsummer-fantasy-days",
    source: "/musics/2.1--fantasy-resort-theme-midsummer-fantasy-days.mp3",
    duration: 309,
    created_at: new Date("2025-12-16"),
    ...Artists["2.1"],
  },
  {
    title: "Miasmic Fiend Boss Theme",
    title_id: "miasmic-fiend-boss-theme",
    source: "/musics/2.1--miasmic-fiend-boss-theme.mp3",
    duration: 321,
    created_at: new Date("2025-12-16"),
    ...Artists["2.1"],
  },
  {
    title: "Mirage Ocean Angling - Powerful Catch Theme (Fishing)",
    title_id: "mirage-ocean-angling-powerful-catch-theme-fishing",
    source:
      "/musics/2.1--mirage-ocean-angling-powerful-catch-theme-fishing.mp3",
    duration: 102,
    created_at: new Date("2025-12-16"),
    ...Artists["2.1"],
  },
  {
    title: "Sailume Bay Theme",
    title_id: "sailume-bay-theme",
    source: "/musics/2.1--sailume-bay-theme.mp3",
    duration: 249,
    created_at: new Date("2025-12-16"),
    ...Artists["2.1"],
  },
  {
    title: "Surfing Minigame - Blazing Waves Theme 1",
    title_id: "surfing-minigame-blazing-waves-theme-1",
    source: "/musics/2.1--surfing-minigame-blazing-waves-theme-1.mp3",
    duration: 182,
    created_at: new Date("2025-12-16"),
    ...Artists["2.1"],
  },
  {
    title: "Surfing Minigame - Blazing Waves Theme 2",
    title_id: "surfing-minigame-blazing-waves-theme-2",
    source: "/musics/2.1--surfing-minigame-blazing-waves-theme-2.mp3",
    duration: 147,
    created_at: new Date("2025-12-16"),
    ...Artists["2.1"],
  },
  {
    title: "Tales of Midsummer Dreams Battle Theme (HQ Ver.)",
    title_id: "tales-of-midsummer-dreams-battle-theme-hq-ver",
    source: "/musics/2.1--tales-of-midsummer-dreams-battle-theme-hq-ver.mp3",
    duration: 216,
    created_at: new Date("2025-12-16"),
    ...Artists["2.1"],
  },
  {
    title: "Tales of Midsummer Dreams Theme (HQ Ver.)",
    title_id: "tales-of-midsummer-dreams-theme-hq-ver",
    source: "/musics/2.1--tales-of-midsummer-dreams-theme-hq-ver.mp3",
    duration: 192,
    created_at: new Date("2025-12-16"),
    ...Artists["2.1"],
  },
  {
    title: "The Last Way Out Theme",
    title_id: "the-last-way-out-theme",
    source: "/musics/2.1--the-last-way-out-theme.mp3",
    duration: 107,
    created_at: new Date("2025-12-16"),
    ...Artists["2.1"],
  },
  {
    title: "Zenith's Lingering Light - Waifei Peninsula Battle Theme",
    title_id: "zenith-s-lingering-light-waifei-peninsula-battle-theme",
    source:
      "/musics/2.1--zenith-s-lingering-light-waifei-peninsula-battle-theme.mp3",
    duration: 463,
    created_at: new Date("2025-12-16"),
    ...Artists["2.1"],
  },
  ...YuzuhaTracks,
].map((track) => ({
  ...track,
  ...Albums["2.1"],
}));
