import { Track } from "@/types/track.type";
import { Albums } from "../albums";
import { Artists } from "../artists";
import { IsoldeTracks } from "./isolde";

export const Album22Tracks: Track[] = [
  {
    title: "A Risky Operation Theme",
    title_id: "a-risky-operation-theme",
    source: "/musics/2.2--a-risky-operation-theme.mp3",
    duration: 148,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "All's Well That Ends Well Theme",
    title_id: "all-s-well-that-ends-well-theme",
    source: "/musics/2.2--all-s-well-that-ends-well-theme.mp3",
    duration: 167,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Blitz and Aegis Theme",
    title_id: "blitz-and-aegis-theme",
    source: "/musics/2.2--blitz-and-aegis-theme.mp3",
    duration: 46,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Defense Force Base Theme",
    title_id: "defense-force-base-theme",
    source: "/musics/2.2--defense-force-base-theme.mp3",
    duration: 148,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Do Not Go Gentle Into That Good Night - Teaser Theme",
    title_id: "do-not-go-gentle-into-that-good-night-teaser-theme",
    source:
      "/musics/2.2--do-not-go-gentle-into-that-good-night-teaser-theme.mp3",
    duration: 137,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "FURY ON (Instrumental)",
    title_id: "fury-on-instrumental",
    source: "/musics/2.2--fury-on-instrumental.mp3",
    duration: 193,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "FURY ON (With Lyrics - Orphie Magus EP)",
    title_id: "fury-on-with-lyrics-orphie-magus-ep",
    source: "/musics/2.2--fury-on-with-lyrics-orphie-magus-ep.mp3",
    duration: 193,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Gunshots of Vengeance Theme",
    title_id: "gunshots-of-vengeance-theme",
    source: "/musics/2.2--gunshots-of-vengeance-theme.mp3",
    duration: 47,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Mutated Flower Theme",
    title_id: "mutated-flower-theme",
    source: "/musics/2.2--mutated-flower-theme.mp3",
    duration: 144,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Obol Gear Up Theme",
    title_id: "obol-gear-up-theme",
    source: "/musics/2.2--obol-gear-up-theme.mp3",
    duration: 41,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Obol Squad Theme",
    title_id: "obol-squad-theme",
    source: "/musics/2.2--obol-squad-theme.mp3",
    duration: 172,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Peace",
    title_id: "peace",
    source: "/musics/2.2--peace.mp3",
    duration: 161,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Problem Soldier Boot Camp Event Theme - Chaos Delta",
    title_id: "problem-soldier-boot-camp-event-theme-chaos-delta",
    source:
      "/musics/2.2--problem-soldier-boot-camp-event-theme-chaos-delta.mp3",
    duration: 181,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Rhythm Rave Event Theme - Burning Desires",
    title_id: "rhythm-rave-event-theme-burning-desires",
    source: "/musics/2.2--rhythm-rave-event-theme-burning-desires.mp3",
    duration: 79,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Rhythm Rave Event Theme - My Curse, My Fate",
    title_id: "rhythm-rave-event-theme-my-curse-my-fate",
    source: "/musics/2.2--rhythm-rave-event-theme-my-curse-my-fate.mp3",
    duration: 89,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Rhythm Rave Event Theme - Original Me",
    title_id: "rhythm-rave-event-theme-original-me",
    source: "/musics/2.2--rhythm-rave-event-theme-original-me.mp3",
    duration: 95,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Rhythm Rave Event Theme - Uniforms, Shark Tails, Scissors",
    title_id: "rhythm-rave-event-theme-uniforms-shark-tails-scissors",
    source:
      "/musics/2.2--rhythm-rave-event-theme-uniforms-shark-tails-scissors.mp3",
    duration: 92,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Rhythm Rave Event Theme - Wonderland Trickery",
    title_id: "rhythm-rave-event-theme-wonderland-trickery",
    source: "/musics/2.2--rhythm-rave-event-theme-wonderland-trickery.mp3",
    duration: 108,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Rhythm Rave Event Theme - pinKing",
    title_id: "rhythm-rave-event-theme-pinking",
    source: "/musics/2.2--rhythm-rave-event-theme-pinking.mp3",
    duration: 78,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Sacrifice Crisis Theme",
    title_id: "sacrifice-crisis-theme",
    source: "/musics/2.2--sacrifice-crisis-theme.mp3",
    duration: 63,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Seed Agent Story - Exploration Theme",
    title_id: "seed-agent-story-exploration-theme",
    source: "/musics/2.2--seed-agent-story-exploration-theme.mp3",
    duration: 116,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Seed Flora Theme 1 (Extended Ver.)",
    title_id: "seed-flora-theme-1-extended-ver",
    source: "/musics/2.2--seed-flora-theme-1-extended-ver.mp3",
    duration: 201,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Seed Flora Theme 2 (Extended Ver.)",
    title_id: "seed-flora-theme-2-extended-ver",
    source: "/musics/2.2--seed-flora-theme-2-extended-ver.mp3",
    duration: 152,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Seed Flora Theme 3 - The Promised Land (Extended Ver.)",
    title_id: "seed-flora-theme-3-the-promised-land-extended-ver",
    source:
      "/musics/2.2--seed-flora-theme-3-the-promised-land-extended-ver.mp3",
    duration: 199,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Seed Flora Theme (Variation)",
    title_id: "seed-flora-theme-variation",
    source: "/musics/2.2--seed-flora-theme-variation.mp3",
    duration: 167,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Seed Theme - Final Message",
    title_id: "seed-theme-final-message",
    source: "/musics/2.2--seed-theme-final-message.mp3",
    duration: 312,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Seed's Safe House Theme",
    title_id: "seed-s-safe-house-theme",
    source: "/musics/2.2--seed-s-safe-house-theme.mp3",
    duration: 197,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Tearforged Blossoms - Valley of Flowers Theme",
    title_id: "tearforged-blossoms-valley-of-flowers-theme",
    source: "/musics/2.2--tearforged-blossoms-valley-of-flowers-theme.mp3",
    duration: 77,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "The Art of Hospitality Theme",
    title_id: "the-art-of-hospitality-theme",
    source: "/musics/2.2--the-art-of-hospitality-theme.mp3",
    duration: 179,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "The Defector Boss Theme - The Final Duel",
    title_id: "the-defector-boss-theme-the-final-duel",
    source: "/musics/2.2--the-defector-boss-theme-the-final-duel.mp3",
    duration: 285,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "The Defiler Boss Theme - Unextinguished Through the Night (Battle)",
    title_id:
      "the-defiler-boss-theme-unextinguished-through-the-night-battle-theme",
    source:
      "/musics/2.2--the-defiler-boss-theme-unextinguished-through-the-night-battle-theme.mp3",
    duration: 356,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "The Defiler Boss Theme - Unextinguished Through the Night (Outro)",
    title_id: "the-defiler-boss-theme-unextinguished-through-the-night-outro",
    source:
      "/musics/2.2--the-defiler-boss-theme-unextinguished-through-the-night-outro.mp3",
    duration: 327,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "The Final Duel",
    title_id: "the-final-duel",
    source: "/musics/2.2--the-final-duel.mp3",
    duration: 235,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Hollow Zero Theme - Chaos Alpha (Shiyu Defense)",
    title_id: "hollow-zero-theme-chaos-alpha-shiyu-defense",
    source: "/musics/2.2--hollow-zero-theme-chaos-alpha-shiyu-defense.mp3",
    duration: 260,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Hollow Zero Theme - Chaos Beta (Shiyu Defense)",
    title_id: "hollow-zero-theme-chaos-beta-shiyu-defense",
    source: "/musics/2.2--hollow-zero-theme-chaos-beta-shiyu-defense.mp3",
    duration: 313,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  {
    title: "Soldier 11 Agent Story Theme",
    title_id: "soldier-11-agent-story-theme",
    source: "/musics/2.2--soldier-11-agent-story-theme.mp3",
    duration: 272,
    created_at: new Date("2025-12-16"),
    ...Artists["2.2"],
  },
  ...IsoldeTracks,
].map((track) => ({
  ...track,
  ...Albums["2.2"],
}));
