import { Track } from "@/types/track.type";
import { Albums } from "../albums";
import { Artists } from "../artists";
import { LuciaTracks } from "./lucia";

export const Album23Tracks: Track[] = [
  {
    title: "Waking from the dream",
    title_id: "waking-from-the-dream",
    source: "/musics/2.3--waking-from-the-dream-theme.mp3",
    duration: 55,
    created_at: new Date("2025-10-16"),
    ...Artists["2.3"],
  },
  {
    title: "Memories of Dreams Bygone - Teaser",
    title_id: "memories-of-dreams-bygone-teaser",
    source: "/musics/2.3--memories-of-dreams-bygone-teaser.mp3",
    duration: 161,
    created_at: new Date("2025-10-16"),
    ...Artists["2.3"],
  },
  {
    title: "Ah-Deh Wandering Hunter Boss - Combat Ending Theme",
    title_id: "ah-deh-wandering-hunter-boss-combat-ending-theme",
    source: "/musics/2.3--ah-deh-wandering-hunter-boss-combat-ending-theme.mp3",
    duration: 67,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Ah-Deh Wandering Hunter Boss - Combat Theme",
    title_id: "ah-deh-wandering-hunter-boss-combat-theme",
    source: "/musics/2.3--ah-deh-wandering-hunter-boss-combat-theme.mp3",
    duration: 108,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Drowned Ideal Boss Theme",
    title_id: "drowned-ideal-boss-theme",
    source: "/musics/2.3--drowned-ideal-boss-theme.mp3",
    duration: 204,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Drowned Ideal Boss Theme (Story Ver.)",
    title_id: "drowned-ideal-boss-theme-story-ver",
    source: "/musics/2.3--drowned-ideal-boss-theme-story-ver.mp3",
    duration: 154,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "The Silver Arrival Theme",
    title_id: "the-silver-arrival-theme",
    source: "/musics/2.3--the-silver-arrival-theme.mp3",
    duration: 35,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Threshold Simulation Theme",
    title_id: "threshold-simulation-theme",
    source: "/musics/2.3--threshold-simulation-theme.mp3",
    duration: 338,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Threshold Simulation Theme 2",
    title_id: "threshold-simulation-theme-2",
    source: "/musics/2.3--threshold-simulation-theme-2.mp3",
    duration: 343,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Timesworn Hills Battle Theme 1 (Lemnian Hollow)",
    title_id: "timesworn-hills-battle-theme-1-lemnian-hollow",
    source: "/musics/2.3--timesworn-hills-battle-theme-1-lemnian-hollow.mp3",
    duration: 164,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Timesworn Hills Battle Theme 2 (Lemnian Hollow)",
    title_id: "timesworn-hills-battle-theme-2-lemnian-hollow",
    source: "/musics/2.3--timesworn-hills-battle-theme-2-lemnian-hollow.mp3",
    duration: 164,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Timesworn Hills Exploration Theme (Lemnian Hollow)",
    title_id: "timesworn-hills-exploration-theme-lemnian-hollow",
    source: "/musics/2.3--timesworn-hills-exploration-theme-lemnian-hollow.mp3",
    duration: 209,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Timesworn Hills Theme",
    title_id: "timesworn-hills-theme",
    source: "/musics/2.3--timesworn-hills-theme.mp3",
    duration: 271,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Dreams of the Timesworn Hills OST",
    title_id: "dreams-of-the-timesworn-hills-ost",
    source: "/musics/2.3--dreams-of-the-timesworn-hills-ost.mp3",
    duration: 216,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Threshold Simulation Theme 1 (HQ Ver.)",
    title_id: "threshold-simulation-theme-1-hq-ver",
    source: "/musics/2.3--threshold-simulation-theme-1-hq-ver.mp3",
    duration: 670,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Threshold Simulation Theme 2 (HQ Ver.)",
    title_id: "threshold-simulation-theme-2-hq-ver",
    source: "/musics/2.3--threshold-simulation-theme-2-hq-ver.mp3",
    duration: 670,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "A Moment's Light Theme",
    title_id: "a-moment-s-light-theme",
    source: "/musics/2.3--a-moment-s-light-theme.mp3",
    duration: 67,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Echoes of the Hollow Theme",
    title_id: "echoes-of-the-hollow-theme",
    source: "/musics/2.3--echoes-of-the-hollow-theme.mp3",
    duration: 70,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Hollow Tour Service Theme",
    title_id: "hollow-tour-service-theme",
    source: "/musics/2.3--hollow-tour-service-theme.mp3",
    duration: 189,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Escape from the Town Theme",
    title_id: "escape-from-the-town-theme",
    source: "/musics/2.3--escape-from-the-town-theme.mp3",
    duration: 114,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Like Enemies Like Friends Theme",
    title_id: "like-enemies-like-friends-theme",
    source: "/musics/2.3--like-enemies-like-friends-theme.mp3",
    duration: 30,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Yunkui Summit Faction Theme",
    title_id: "yunkui-summit-faction-theme",
    source: "/musics/2.3--yunkui-summit-faction-theme.mp3",
    duration: 128,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Blazewood (Dream Ver.) - When Dreams Remain Unfinished Event Theme",
    title_id: "blazewood-dream-ver-when-dreams-remain-unfinished-event-theme",
    source:
      "/musics/2.3--blazewood-dream-ver-when-dreams-remain-unfinished-event-theme.mp3",
    duration: 231,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title:
      "Port Elpis (Dream Ver.) - When Dreams Remain Unfinished Event Theme",
    title_id: "port-elpis-dream-ver-when-dreams-remain-unfinished-event-theme",
    source:
      "/musics/2.3--port-elpis-dream-ver-when-dreams-remain-unfinished-event-theme.mp3",
    duration: 414,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title:
      "Forget-Me-Not Theme - This Little Maneuver's Gonna Cost Us 51 Years",
    title_id:
      "forget-me-not-theme-this-little-maneuver-s-gonna-cost-us-51-years",
    source:
      "/musics/2.3--forget-me-not-theme-this-little-maneuver-s-gonna-cost-us-51-years.mp3",
    duration: 109,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "You've Got Nowhere to Go Theme",
    title_id: "you-ve-got-nowhere-to-go-theme",
    source: "/musics/2.3--you-ve-got-nowhere-to-go-theme.mp3",
    duration: 40,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Dream Into the Outer Ring Theme",
    title_id: "dream-into-the-outer-ring-theme",
    source: "/musics/2.3--dream-into-the-outer-ring-theme.mp3",
    duration: 177,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Yidhari Dream Combat Theme - When Dreams Remain Unfinished Event",
    title_id: "yidhari-dream-combat-theme-when-dreams-remain-unfinished-event",
    source:
      "/musics/2.3--yidhari-dream-combat-theme-when-dreams-remain-unfinished-event.mp3",
    duration: 160,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Yidhari Dream Combat Theme 2 - When Dreams Remain Unfinished Event",
    title_id:
      "yidhari-dream-combat-theme-2-when-dreams-remain-unfinished-event",
    source:
      "/musics/2.3--yidhari-dream-combat-theme-2-when-dreams-remain-unfinished-event.mp3",
    duration: 160,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Yidhari's Past Dream Theme - When Dreams Remain Unfinished Event",
    title_id: "yidhari-s-past-dream-theme-when-dreams-remain-unfinished-event",
    source:
      "/musics/2.3--yidhari-s-past-dream-theme-when-dreams-remain-unfinished-event.mp3",
    duration: 472,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Shadow of Extradition OST",
    title_id: "shadow-of-extradition-ost",
    source: "/musics/2.3--shadow-of-extradition-ost.mp3",
    duration: 230,
    created_at: new Date("2025-12-26"),
    ...Artists["2.3"],
  },
  ...LuciaTracks,
].map((track) => ({
  ...track,
  ...Albums["2.3"],
}));
