import { Track } from "@/types/track.type";
import { Albums } from "../albums";
import { Artists } from "../artists";
import { LuciaTracks } from "./lucia";

export const Album23Tracks: Track[] = [
  {
    title: "Waking from the dream",
    title_id: "waking-from-the-dream",
    source: "/musics/2.3--waking-from-the-dream-theme.mp3",
    duration: 55,
    created_at: new Date("2025-10-16"),
    ...Artists["2.3"],
  },
  {
    title: "Memories of Dreams Bygone - Teaser",
    title_id: "memories-of-dreams-bygone-teaser",
    source: "/musics/2.3--memories-of-dreams-bygone-teaser.mp3",
    duration: 161,
    created_at: new Date("2025-10-16"),
    ...Artists["2.3"],
  },
  {
    title: "Ah-Deh Wandering Hunter Boss - Combat Ending Theme",
    title_id: "ah-deh-wandering-hunter-boss-combat-ending-theme",
    source: "/musics/2.3--ah-deh-wandering-hunter-boss-combat-ending-theme.mp3",
    duration: 67,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Ah-Deh Wandering Hunter Boss - Combat Theme",
    title_id: "ah-deh-wandering-hunter-boss-combat-theme",
    source: "/musics/2.3--ah-deh-wandering-hunter-boss-combat-theme.mp3",
    duration: 108,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Drowned Ideal Boss Theme",
    title_id: "drowned-ideal-boss-theme",
    source: "/musics/2.3--drowned-ideal-boss-theme.mp3",
    duration: 204,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Drowned Ideal Boss Theme (Story Ver.)",
    title_id: "drowned-ideal-boss-theme-story-ver",
    source: "/musics/2.3--drowned-ideal-boss-theme-story-ver.mp3",
    duration: 154,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Phaethon Saving Yidhari Theme",
    title_id: "phaethon-saving-yidhari-theme",
    source: "/musics/2.3--phaethon-saving-yidhari-theme.mp3",
    duration: 221,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "The Silver Arrival Theme",
    title_id: "the-silver-arrival-theme",
    source: "/musics/2.3--the-silver-arrival-theme.mp3",
    duration: 35,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Threshold Simulation Theme",
    title_id: "threshold-simulation-theme",
    source: "/musics/2.3--threshold-simulation-theme.mp3",
    duration: 338,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Timesworn Hills Battle Theme 1 (Lemnian Hollow)",
    title_id: "timesworn-hills-battle-theme-1-lemnian-hollow",
    source: "/musics/2.3--timesworn-hills-battle-theme-1-lemnian-hollow.mp3",
    duration: 164,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Timesworn Hills Battle Theme 2 (Lemnian Hollow)",
    title_id: "timesworn-hills-battle-theme-2-lemnian-hollow",
    source: "/musics/2.3--timesworn-hills-battle-theme-2-lemnian-hollow.mp3",
    duration: 164,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Timesworn Hills Exploration Theme (Lemnian Hollow)",
    title_id: "timesworn-hills-exploration-theme-lemnian-hollow",
    source: "/musics/2.3--timesworn-hills-exploration-theme-lemnian-hollow.mp3",
    duration: 209,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  {
    title: "Timesworn Hills Theme",
    title_id: "timesworn-hills-theme",
    source: "/musics/2.3--timesworn-hills-theme.mp3",
    duration: 271,
    created_at: new Date("2025-01-16"),
    ...Artists["2.3"],
  },
  ...LuciaTracks,
].map((track) => ({
  ...track,
  ...Albums["2.3"],
}));
