import { Track } from "@/types/track.type";
import { Albums } from "../albums";
import { Artists } from "../artists";

export const Album24Tracks: Track[] = [
  {
    title: "Banyue Battle Theme",
    title_id: "banyue-battle-theme",
    source: "/musics/2.4--banyue-battle-theme.mp3",
    duration: 293,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
  {
    title: "Banyue Entrance Theme - Close Call",
    title_id: "banyue-entrance-theme-close-call",
    source: "/musics/2.4--banyue-entrance-theme--close-call.mp3",
    duration: 41,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
  {
    title: "Banyue Past Theme - Slaughterer",
    title_id: "banyue-past-theme-slaughterer",
    source: "/musics/2.4--banyue-past-theme--slaughterer.mp3",
    duration: 56,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
  {
    title: "Dialyn Entrance Theme - Perfect Customer Service",
    title_id: "dialyn-entrance-theme-perfect-customer-service",
    source: "/musics/2.4--dialyn-entrance-theme--perfect-customer-service.mp3",
    duration: 38,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
  {
    title: "En-Nah Chess Saga - Menu Theme (HQ Ver.)",
    title_id: "en-nah-chess-saga-menu-theme-hq-ver",
    source: "/musics/2.4--en-nah-chess-saga-event-menu-theme-hq-ver.mp3",
    duration: 257,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
  {
    title: "En-Nah Chess Saga - Theme 1 (HQ Ver.)",
    title_id: "en-nah-chess-saga-theme-1-hq-ver",
    source: "/musics/2.4--en-nah-chess-saga-event-theme-1-hq-ver.mp3",
    duration: 375,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
  {
    title: "En-Nah Chess Saga - Theme 2 (HQ Ver.)",
    title_id: "en-nah-chess-saga-theme-2-hq-ver",
    source: "/musics/2.4--en-nah-chess-saga-event-theme-2-hq-ver.mp3",
    duration: 291,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
  {
    title: "Fallen Mecha Stronghold Theme - Neo Golden Mecha Event",
    title_id: "fallen-mecha-stronghold-theme-neo-golden-mecha-event",
    source:
      "/musics/2.4--fallen-mecha-stronghold-theme-neo-golden-mecha-event.mp3",
    duration: 295,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
  {
    title: "Moment of Respite Theme",
    title_id: "moment-of-respite-theme",
    source: "/musics/2.4--moment-of-respite-theme.mp3",
    duration: 139,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
  {
    title: "Nightmare Strikes Again Theme",
    title_id: "nightmare-strikes-again-theme",
    source: "/musics/2.4--nightmare-strikes-again-theme.mp3",
    duration: 59,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
  {
    title: "Old Mining Site Battle Theme 1",
    title_id: "old-mining-site-battle-theme-1",
    source: "/musics/2.4--old-mining-site-battle-theme-1.mp3",
    duration: 358,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
  {
    title: "Old Mining Site Battle Theme 2",
    title_id: "old-mining-site-battle-theme-2",
    source: "/musics/2.4--old-mining-site-battle-theme-2.mp3",
    duration: 359,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
  {
    title: "Old Mining Site Exploration Theme (Lemnian Hollow)",
    title_id: "old-mining-site-exploration-theme-lemnian-hollow",
    source:
      "/musics/2.4--old-mining-site-exploration-theme--lemnian-hollow.mp3",
    duration: 292,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
  {
    title: "Old Mining Site Theme (Lemnian Hollow)",
    title_id: "old-mining-site-theme-lemnian-hollow",
    source: "/musics/2.4--old-mining-site-theme--lemnian-hollow.mp3",
    duration: 505,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
  {
    title: "Old Mining Site Exploration Theme (Lemnian Hollow Ver.2)",
    title_id: "old-mining-site-exploration-theme-lemnian-hollow-ver-2",
    source:
      "/musics/2.4--old-mining-site-exploration-theme--lemnian-hollow-ver-2.mp3",
    duration: 292,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
  {
    title: "On the Precipice of the Abyss - Teaser Theme",
    title_id: "on-the-precipice-of-the-abyss-teaser-theme",
    source: "/musics/2.4--on-the-precipice-of-the-abyss-teaser-theme.mp3",
    duration: 158,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
  {
    title: "Sarah Theme - Return from the End",
    title_id: "sarah-theme-return-from-the-end",
    source: "/musics/2.4--sarah-theme--return-from-the-end.mp3",
    duration: 160,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
  {
    title: "Sobek Boss Theme - Phase 1",
    title_id: "sobek-boss-theme-phase-1",
    source: "/musics/2.4--sobek-boss-theme-phase-1.mp3",
    duration: 234,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
  {
    title: "The Thrall & Sobek Boss Theme - The Creator Embryonic Form",
    title_id: "the-thrall-and-sobek-boss-theme-the-creator-embryonic-form",
    source:
      "/musics/2.4--the-thrall-and-sobek-boss-theme--the-creator-embryonic-form.mp3",
    duration: 486,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
  {
    title: "The Wish Behind the Nightmare Theme",
    title_id: "the-wish-behind-the-nightmare-theme",
    source: "/musics/2.4--the-wish-behind-the-nightmare-theme.mp3",
    duration: 76,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
  {
    title: "Unfinished Judgment Theme",
    title_id: "unfinished-judgment-theme",
    source: "/musics/2.4--unfinished-judgment-theme.mp3",
    duration: 66,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
  {
    title: "What Was Taken Theme",
    title_id: "what-was-taken-theme",
    source: "/musics/2.4--what-was-taken-theme.mp3",
    duration: 27,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
  {
    title: "Ye Shiyuan the Thrall - Boss Theme",
    title_id: "ye-shiyuan-the-thrall-boss-theme",
    source: "/musics/2.4--ye-shiyuan-the-thrall-boss-theme.mp3",
    duration: 370,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
  {
    title:
      "Ye Shunguang Unleashes Qingming Sword Theme - The Moment of Final Choice",
    title_id:
      "ye-shunguang-unleashes-qingming-sword-theme-the-moment-of-final-choice",
    source:
      "/musics/2.4--ye-shunguang-unleashes-qingming-sword-theme--the-moment-of-final-choice.mp3",
    duration: 138,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
  {
    title: "Banyue EP - I Ask",
    title_id: "banyue-ep-i-ask",
    source: "/musics/2.4--banyue-ep--i-ask.mp3",
    duration: 194,
    created_at: new Date("2025-12-16"),
    ...Artists["2.4"],
  },
].map((track) => ({
  ...track,
  ...Albums["2.4"],
}));
