import { Albums } from "../albums";
import { Artists } from "../artists";

export const Album25Tracks = [
  {
    title: "Ye Shunguang EP - A Thousand First Meetings",
    title_id: "ye-shunguang-ep--a-thousand-first-meetings",
    source: "/musics/2.5--ye-shunguang-ep--a-thousand-first-meetings.mp3",
    duration: 292,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "A Close Call Theme",
    title_id: "a-close-call-theme",
    source: "/musics/2.5--a-close-call-theme.mp3",
    duration: 42,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Buyan Store Theme",
    title_id: "buyan-store-theme",
    source: "/musics/2.5--buyan-store-theme.mp3",
    duration: 213,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Lockspring Boss Theme",
    title_id: "lockspring-boss-theme",
    source: "/musics/2.5--lockspring-boss-theme.mp3",
    duration: 144,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Lumite Mine Battle Theme",
    title_id: "lumite-mine-battle-theme",
    source: "/musics/2.5--lumite-mine-battle-theme.mp3",
    duration: 278,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Lumite Mine Exploration Theme",
    title_id: "lumite-mine-exploration-theme",
    source: "/musics/2.5--lumite-mine-exploration-theme.mp3",
    duration: 192,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Lumite Mine Theme",
    title_id: "lumite-mine-theme",
    source: "/musics/2.5--lumite-mine-theme.mp3",
    duration: 236,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Must-Do Task Theme",
    title_id: "must-do-task-theme",
    source: "/musics/2.5--must-do-task-theme.mp3",
    duration: 52,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Old Port Factory Battle Theme",
    title_id: "old-port-factory-battle-theme",
    source: "/musics/2.5--old-port-factory-battle-theme.mp3",
    duration: 157,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Old Port Factory Exploration Theme",
    title_id: "old-port-factory-exploration-theme",
    source: "/musics/2.5--old-port-factory-exploration-theme.mp3",
    duration: 192,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Old Port Factory Theme",
    title_id: "old-port-factory-theme",
    source: "/musics/2.5--old-port-factory-theme.mp3",
    duration: 172,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Phaethon's Eyes Power Awakening Theme - First Signs of Change",
    title_id: "phaethon-s-eyes-power-awakening-theme-first-signs-of-change",
    source: "/musics/2.5--phaethon-s-eyes-power-awakening-theme-first-signs-of-change.mp3",
    duration: 167,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Phaethon Saving Ye Shunguang Theme - The Hand in the Dark",
    title_id: "phaethon-saving-ye-shunguang-theme-the-hand-in-the-dark",
    source: "/musics/2.5--phaethon-saving-ye-shunguang-theme-the-hand-in-the-dark.mp3",
    duration: 89,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Phantoms of the Past Theme",
    title_id: "phantoms-of-the-past-theme",
    source: "/musics/2.5--phantoms-of-the-past-theme.mp3",
    duration: 219,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Polarity Calibration Theme",
    title_id: "polarity-calibration-theme",
    source: "/musics/2.5--polarity-calibration-theme.mp3",
    duration: 97,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Porcelume Processing Base Battle Theme",
    title_id: "porcelume-processing-base-battle-theme",
    source: "/musics/2.5--porcelume-processing-base-battle-theme.mp3",
    duration: 158,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Porcelume Processing Base Exploration Theme",
    title_id: "porcelume-processing-base-exploration-theme",
    source: "/musics/2.5--porcelume-processing-base-exploration-theme.mp3",
    duration: 192,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Porcelume Processing Base Theme",
    title_id: "porcelume-processing-base-theme",
    source: "/musics/2.5--porcelume-processing-base-theme.mp3",
    duration: 172,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Qingming Realm Battle Theme Sword Seeker Chronicles",
    title_id: "qingming-realm-battle-theme-sword-seeker-chronicles",
    source: "/musics/2.5--qingming-realm-battle-theme-sword-seeker-chronicles.mp3",
    duration: 271,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Qingming Realm Exploration Theme 1 Sword Seeker Chronicles",
    title_id: "qingming-realm-exploration-theme-1-sword-seeker-chronicles",
    source: "/musics/2.5--qingming-realm-exploration-theme-1-sword-seeker-chronicles.mp3",
    duration: 213,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Qingming Realm Exploration Theme 2 Sword Seeker Chronicles",
    title_id: "qingming-realm-exploration-theme-2-sword-seeker-chronicles",
    source: "/musics/2.5--qingming-realm-exploration-theme-2-sword-seeker-chronicles.mp3",
    duration: 232,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Qingming Realm Exploration Theme 3 Sword Seeker Chronicles",
    title_id: "qingming-realm-exploration-theme-3-sword-seeker-chronicles",
    source: "/musics/2.5--qingming-realm-exploration-theme-3-sword-seeker-chronicles.mp3",
    duration: 257,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Season 2 Retrospective - Journeying Through Waifei 2025 Theme",
    title_id: "season-2-retrospective-journeying-through-waifei-2025-theme",
    source: "/musics/2.5--season-2-retrospective-journeying-through-waifei-2025-theme.mp3",
    duration: 75,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Split into Five Forces Theme",
    title_id: "split-into-five-forces-theme",
    source: "/musics/2.5--split-into-five-forces-theme.mp3",
    duration: 24,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "The Creator Boss Theme Primordial Nightmare",
    title_id: "the-creator-boss-theme-primordial-nightmare",
    source: "/musics/2.5--the-creator-boss-theme-primordial-nightmare.mp3",
    duration: 296,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "The Creator Cocoon Theme Provenance of Malice",
    title_id: "the-creator-cocoon-theme-provenance-of-malice",
    source: "/musics/2.5--the-creator-cocoon-theme-provenance-of-malice.mp3",
    duration: 390,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Their Gaze Theme",
    title_id: "their-gaze-theme",
    source: "/musics/2.5--their-gaze-theme.mp3",
    duration: 32,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Their Whispers Theme",
    title_id: "their-whispers-theme",
    source: "/musics/2.5--their-whispers-theme.mp3",
    duration: 102,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "To Be Fuel for the Night Teaser Theme",
    title_id: "to-be-fuel-for-the-night-teaser-theme",
    source: "/musics/2.5--to-be-fuel-for-the-night-teaser-theme.mp3",
    duration: 145,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Xiao Guang's Music Box Theme",
    title_id: "xiao-guang-s-music-box-theme",
    source: "/musics/2.5--xiao-guang-s-music-box-theme.mp3",
    duration: 246,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Ye Shunguang Music Box Theme Variation",
    title_id: "ye-shunguang-music-box-theme-variation",
    source: "/musics/2.5--ye-shunguang-music-box-theme-variation.mp3",
    duration: 149,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Ye Shunguang Theme",
    title_id: "ye-shunguang-theme",
    source: "/musics/2.5--ye-shunguang-theme.mp3",
    duration: 36,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Ye Shunguang's Sacrifice Theme - The Final Choice",
    title_id: "ye-shunguang-s-sacrifice-theme-the-final-choice",
    source: "/musics/2.5--ye-shunguang-s-sacrifice-theme-the-final-choice.mp3",
    duration: 46,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Zhao EP - Tiny Giant with English Lyrics",
    title_id: "zhao-ep-tiny-giant-with-english-lyrics",
    source: "/musics/2.5--zhao-ep-tiny-giant-with-english-lyrics.mp3",
    duration: 182,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Zhao Heroic Moment Theme - Loss and Gain",
    title_id: "zhao-heroic-moment-theme-loss-and-gain",
    source: "/musics/2.5--zhao-heroic-moment-theme-loss-and-gain.mp3",
    duration: 43,
    created_at: new Date("2025-12-26"),
    ...Artists["2.5"],
  },
  {
    title: "Ye Shunguang Relaxing Theme",
    title_id: "ye-shunguang-relaxing-theme",
    source: "/musics/2.5--ye-shunguang-relaxing-theme.mp3",
    duration: 155,
    created_at: new Date("2026-01-02"),
    ...Artists["2.5"],
  },
].map((track) => ({
  ...track,
  ...Albums["2.5"],
}));
