import { Track } from "@/types/track.type";
import { Albums } from "../albums";
import { Artists } from "../artists";

export const Album26Tracks: Track[] = [
  {
    title: "404 Error Livehouse Theme - Under Clear Skies",
    title_id: "404-error-livehouse-theme-under-clear-skies",
    source: "/musics/2.6--404-error-livehouse-theme-under-clear-skies.mp3",
    duration: 240,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "About the Wishing Sprite Theme",
    title_id: "about-the-wishing-sprite-theme",
    source: "/musics/2.6--about-the-wishing-sprite-theme.mp3",
    duration: 146,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Angel Loading... - CN Vocal - Aria EP P2 Variation",
    title_id: "angel-loading-cn-vocal-aria-ep-p2-variation",
    source: "/musics/2.6--angel-loading-cn-vocal-aria-ep-p2-variation.mp3",
    duration: 127,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Angel Loading... - Instrumental Version - Aria EP",
    title_id: "angel-loading-instrumental-version-aria-ep",
    source: "/musics/2.6--angel-loading-instrumental-version-aria-ep.mp3",
    duration: 229,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Angel Loading... - JP Vocal - Aria EP P2 Variation",
    title_id: "angel-loading-jp-vocal-aria-ep-p2-variation",
    source: "/musics/2.6--angel-loading-jp-vocal-aria-ep-p2-variation.mp3",
    duration: 127,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Angels of Delusion EP - ReDreaming Angel Instrumental Ver.",
    title_id: "angels-of-delusion-ep-redreaming-angel-instrumental-ver",
    source:
      "/musics/2.6--angels-of-delusion-ep-redreaming-angel-instrumental-ver.mp3",
    duration: 190,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Angels of Delusion First Livestream Ending Theme",
    title_id: "angels-of-delusion-first-livestream-ending-theme",
    source: "/musics/2.6--angels-of-delusion-first-livestream-ending-theme.mp3",
    duration: 394,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title:
      "Angels of Delusion Idol Show 404 Error - Turn Heartbeats Into Tempo",
    title_id:
      "angels-of-delusion-idol-show-404-error-turn-heartbeats-into-tempo",
    source:
      "/musics/2.6--angels-of-delusion-idol-show-404-error-turn-heartbeats-into-tempo.mp3",
    duration: 157,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Aria Boss Theme - Uproar of Old Dreams",
    title_id: "aria-boss-theme-uproar-of-old-dreams",
    source: "/musics/2.6--aria-boss-theme-uproar-of-old-dreams.mp3",
    duration: 237,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Aria Demo Theme - Angel Loading... - P1 Instrumental Ver.",
    title_id: "aria-demo-theme-angel-loading-p1-instrumental-ver",
    source:
      "/musics/2.6--aria-demo-theme-angel-loading-p1-instrumental-ver.mp3",
    duration: 104,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Aria Demo Theme - Prelude - Mechanical Desire CN Vocal",
    title_id: "aria-demo-theme-prelude-mechanical-desire-cn-vocal",
    source:
      "/musics/2.6--aria-demo-theme-prelude-mechanical-desire-cn-vocal.mp3",
    duration: 106,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Aria Demo Theme - Prelude - Mechanical Desire JP Vocal",
    title_id: "aria-demo-theme-prelude-mechanical-desire-jp-vocal",
    source:
      "/musics/2.6--aria-demo-theme-prelude-mechanical-desire-jp-vocal.mp3",
    duration: 106,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Aria EP - Angel Loading... - CN Vocal",
    title_id: "aria-ep-angel-loading-cn-vocal",
    source: "/musics/2.6--aria-ep-angel-loading-cn-vocal.mp3",
    duration: 229,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Aria EP - Angel Loading... - JP Vocal",
    title_id: "aria-ep-angel-loading-jp-vocal",
    source: "/musics/2.6--aria-ep-angel-loading-jp-vocal.mp3",
    duration: 230,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Aria EP - Angel Loading... - P2 Instrumental Ver.",
    title_id: "aria-ep-angel-loading-p2-instrumental-ver",
    source: "/musics/2.6--aria-ep-angel-loading-p2-instrumental-ver.mp3",
    duration: 127,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Aria Theme - Angel Loading... - A Harmony of Delusions Event Ver.",
    title_id: "aria-theme-angel-loading-a-harmony-of-delusions-event-ver",
    source:
      "/musics/2.6--aria-theme-angel-loading-a-harmony-of-delusions-event-ver.mp3",
    duration: 207,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title:
      "BITE Bite Force - A Harmony of Delusions Event Theme Performance Showdown",
    title_id:
      "bite-bite-force-a-harmony-of-delusions-event-theme-performance-showdown",
    source:
      "/musics/2.6--bite-bite-force-a-harmony-of-delusions-event-theme-performance-showdown.mp3",
    duration: 119,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title:
      "Bangboo vs Ethereal Event Theme 1 Grand Marcel Adventure Event Theme",
    title_id:
      "bangboo-vs-ethereal-event-theme-1-grand-marcel-adventure-event-theme",
    source:
      "/musics/2.6--bangboo-vs-ethereal-event-theme-1-grand-marcel-adventure-event-theme.mp3",
    duration: 249,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title:
      "Bangboo vs Ethereal Event Theme 2 Grand Marcel Adventure Event Theme",
    title_id:
      "bangboo-vs-ethereal-event-theme-2-grand-marcel-adventure-event-theme",
    source:
      "/musics/2.6--bangboo-vs-ethereal-event-theme-2-grand-marcel-adventure-event-theme.mp3",
    duration: 237,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Blazing Fist Frenzy - A Harmony of Delusions Event Theme",
    title_id: "blazing-fist-frenzy-a-harmony-of-delusions-event-theme",
    source:
      "/musics/2.6--blazing-fist-frenzy-a-harmony-of-delusions-event-theme.mp3",
    duration: 104,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Buried Memories Theme",
    title_id: "buried-memories-theme",
    source: "/musics/2.6--buried-memories-theme.mp3",
    duration: 116,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Cecilia Special Performance 404 Error - Cersea Siren's Song",
    title_id: "cecilia-special-performance-404-error-cersea-siren-s-song",
    source:
      "/musics/2.6--cecilia-special-performance-404-error-cersea-siren-s-song.mp3",
    duration: 411,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "DAMIDAMI - A Harmony of Delusions Event Theme Solo Note",
    title_id: "damidami-a-harmony-of-delusions-event-theme-solo-note",
    source:
      "/musics/2.6--damidami-a-harmony-of-delusions-event-theme-solo-note.mp3",
    duration: 103,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Duty - A Harmony of Delusions Event Theme Performance Showdown",
    title_id: "duty-a-harmony-of-delusions-event-theme-performance-showdown",
    source:
      "/musics/2.6--duty-a-harmony-of-delusions-event-theme-performance-showdown.mp3",
    duration: 132,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Encore for an Old Dream Teaser Theme",
    title_id: "encore-for-an-old-dream-teaser-theme",
    source: "/musics/2.6--encore-for-an-old-dream-teaser-theme.mp3",
    duration: 149,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Endless Construction Day Day - A Harmony of Delusions Event Theme",
    title_id: "endless-construction-day-day-a-harmony-of-delusions-event-theme",
    source:
      "/musics/2.6--endless-construction-day-day-a-harmony-of-delusions-event-theme.mp3",
    duration: 149,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Fearless - A Harmony of Delusions Event Theme Solo Note",
    title_id: "fearless-a-harmony-of-delusions-event-theme-solo-note",
    source:
      "/musics/2.6--fearless-a-harmony-of-delusions-event-theme-solo-note.mp3",
    duration: 138,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Gilded Carrot Day Theme HQ Ver. - Gilded Impressions",
    title_id: "gilded-carrot-day-theme-hq-ver-gilded-impressions",
    source:
      "/musics/2.6--gilded-carrot-day-theme-hq-ver-gilded-impressions.mp3",
    duration: 153,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Grand Marcel Adventure Theme Ranking",
    title_id: "grand-marcel-adventure-theme-ranking",
    source: "/musics/2.6--grand-marcel-adventure-theme-ranking.mp3",
    duration: 133,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Grand Marcel Adventure Theme",
    title_id: "grand-marcel-adventure-theme",
    source: "/musics/2.6--grand-marcel-adventure-theme.mp3",
    duration: 177,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Gravitational Attraction Event Theme 1 Movie Date",
    title_id: "gravitational-attraction-event-theme-1-movie-date",
    source:
      "/musics/2.6--gravitational-attraction-event-theme-1-movie-date.mp3",
    duration: 228,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Gravitational Attraction Event Theme 2 Movie Date",
    title_id: "gravitational-attraction-event-theme-2-movie-date",
    source:
      "/musics/2.6--gravitational-attraction-event-theme-2-movie-date.mp3",
    duration: 168,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Hold That Grudge Properly - A Harmony of Delusions Event Theme",
    title_id: "hold-that-grudge-properly-a-harmony-of-delusions-event-theme",
    source:
      "/musics/2.6--hold-that-grudge-properly-a-harmony-of-delusions-event-theme.mp3",
    duration: 341,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "I Ask - A Harmony of Delusions Event Theme Solo Note",
    title_id: "i-ask-a-harmony-of-delusions-event-theme-solo-note",
    source:
      "/musics/2.6--i-ask-a-harmony-of-delusions-event-theme-solo-note.mp3",
    duration: 101,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Multiplayer Mode Theme",
    title_id: "multiplayer-mode-theme",
    source: "/musics/2.6--multiplayer-mode-theme.mp3",
    duration: 29,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title:
      "My Enemies - A Harmony of Delusions Event Theme Performance Showdown",
    title_id:
      "my-enemies-a-harmony-of-delusions-event-theme-performance-showdown",
    source:
      "/musics/2.6--my-enemies-a-harmony-of-delusions-event-theme-performance-showdown.mp3",
    duration: 100,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Original Me - A Harmony of Delusions Event Theme Solo Note",
    title_id: "original-me-a-harmony-of-delusions-event-theme-solo-note",
    source:
      "/musics/2.6--original-me-a-harmony-of-delusions-event-theme-solo-note.mp3",
    duration: 95,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title:
      "Perish Together - A Harmony of Delusions Event Theme Performance Showdown",
    title_id:
      "perish-together-a-harmony-of-delusions-event-theme-performance-showdown",
    source:
      "/musics/2.6--perish-together-a-harmony-of-delusions-event-theme-performance-showdown.mp3",
    duration: 102,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title:
      "ReDreaming Angel - A Harmony of Delusions Event Theme Shining Melody",
    title_id:
      "redreaming-angel-a-harmony-of-delusions-event-theme-shining-melody",
    source:
      "/musics/2.6--redreaming-angel-a-harmony-of-delusions-event-theme-shining-melody.mp3",
    duration: 188,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "ReDreaming Angel Chinese Vocal - Angels of Delusion EP",
    title_id: "redreaming-angel-chinese-vocal-angels-of-delusion-ep",
    source:
      "/musics/2.6--redreaming-angel-chinese-vocal-angels-of-delusion-ep.mp3",
    duration: 190,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "ReDreaming Angel Japanese Vocal - Angels of Delusion EP",
    title_id: "redreaming-angel-japanese-vocal-angels-of-delusion-ep",
    source:
      "/musics/2.6--redreaming-angel-japanese-vocal-angels-of-delusion-ep.mp3",
    duration: 190,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "ReDreaming Angel Sunna's Recording Equipment",
    title_id: "redreaming-angel-sunna-s-recording-equipment",
    source: "/musics/2.6--redreaming-angel-sunna-s-recording-equipment.mp3",
    duration: 176,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Sad Guitar - Goodnight. Sweet Dreams Theme",
    title_id: "sad-guitar-goodnight-sweet-dreams-theme",
    source: "/musics/2.6--sad-guitar-goodnight-sweet-dreams-theme.mp3",
    duration: 191,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title:
      "Sampling Dreams - A Harmony of Delusions Event Theme Shining Melody",
    title_id:
      "sampling-dreams-a-harmony-of-delusions-event-theme-shining-melody",
    source:
      "/musics/2.6--sampling-dreams-a-harmony-of-delusions-event-theme-shining-melody.mp3",
    duration: 143,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title:
      "Satellite Idol Bangboo Show 404 Error - ReDreaming Angel Bangboo Ver.",
    title_id:
      "satellite-idol-bangboo-show-404-error-redreaming-angel-bangboo-ver",
    source:
      "/musics/2.6--satellite-idol-bangboo-show-404-error-redreaming-angel-bangboo-ver.mp3",
    duration: 147,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Self-Cultivation Through Food - A Harmony of Delusions Event Theme",
    title_id:
      "self-cultivation-through-food-a-harmony-of-delusions-event-theme",
    source:
      "/musics/2.6--self-cultivation-through-food-a-harmony-of-delusions-event-theme.mp3",
    duration: 126,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Sunna - Exit the Labyrinth of Memories Theme",
    title_id: "sunna-exit-the-labyrinth-of-memories-theme",
    source: "/musics/2.6--sunna-exit-the-labyrinth-of-memories-theme.mp3",
    duration: 183,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Sunna Dilemma Theme",
    title_id: "sunna-dilemma-theme",
    source: "/musics/2.6--sunna-dilemma-theme.mp3",
    duration: 125,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Sunna First Livestream Theme Music Rhythm",
    title_id: "sunna-first-livestream-theme-music-rhythm",
    source: "/musics/2.6--sunna-first-livestream-theme-music-rhythm.mp3",
    duration: 37,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Sunna Fourth Livestream Theme Music Rhythm",
    title_id: "sunna-fourth-livestream-theme-music-rhythm",
    source: "/musics/2.6--sunna-fourth-livestream-theme-music-rhythm.mp3",
    duration: 56,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Sunna Second Livestream Theme Music Rhythm",
    title_id: "sunna-second-livestream-theme-music-rhythm",
    source: "/musics/2.6--sunna-second-livestream-theme-music-rhythm.mp3",
    duration: 77,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title:
      "Sunna Teaser Theme - Hold That Grudge Properly Extended Mix Languages",
    title_id:
      "sunna-teaser-theme-hold-that-grudge-properly-extended-mix-languages",
    source:
      "/musics/2.6--sunna-teaser-theme-hold-that-grudge-properly-extended-mix-languages.mp3",
    duration: 428,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Sunna Third Livestream Theme Music Rhythm",
    title_id: "sunna-third-livestream-theme-music-rhythm",
    source: "/musics/2.6--sunna-third-livestream-theme-music-rhythm.mp3",
    duration: 46,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Surprisingly Smooth Roadshow Theme",
    title_id: "surprisingly-smooth-roadshow-theme",
    source: "/musics/2.6--surprisingly-smooth-roadshow-theme.mp3",
    duration: 38,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "The Forecasters Idol Show 404 Error - ReDreaming Angel",
    title_id: "the-forecasters-idol-show-404-error-redreaming-angel",
    source:
      "/musics/2.6--the-forecasters-idol-show-404-error-redreaming-angel.mp3",
    duration: 374,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Tiny Giant - A Harmony of Delusions Event Theme Solo Note",
    title_id: "tiny-giant-a-harmony-of-delusions-event-theme-solo-note",
    source:
      "/musics/2.6--tiny-giant-a-harmony-of-delusions-event-theme-solo-note.mp3",
    duration: 126,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Tonight's Melody Theme",
    title_id: "tonight-s-melody-theme",
    source: "/musics/2.6--tonight-s-melody-theme.mp3",
    duration: 90,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Tonight's Wish Theme - ReDreaming Angel",
    title_id: "tonight-s-wish-theme-redreaming-angel",
    source: "/musics/2.6--tonight-s-wish-theme-redreaming-angel.mp3",
    duration: 185,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Turn Heartbeats Into Tempo - A Harmony of Delusions Event Theme",
    title_id: "turn-heartbeats-into-tempo-a-harmony-of-delusions-event-theme",
    source:
      "/musics/2.6--turn-heartbeats-into-tempo-a-harmony-of-delusions-event-theme.mp3",
    duration: 174,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Turn Heartbeats Into Tempo Chinese Vocal - Angels of Delusion EP",
    title_id: "turn-heartbeats-into-tempo-chinese-vocal-angels-of-delusion-ep",
    source:
      "/musics/2.6--turn-heartbeats-into-tempo-chinese-vocal-angels-of-delusion-ep.mp3",
    duration: 237,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title:
      "Turn Heartbeats Into Tempo Instrumental Ver. - Angels of Delusion EP",
    title_id:
      "turn-heartbeats-into-tempo-instrumental-ver-angels-of-delusion-ep",
    source:
      "/musics/2.6--turn-heartbeats-into-tempo-instrumental-ver-angels-of-delusion-ep.mp3",
    duration: 237,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Turn Heartbeats Into Tempo Sunna Solo Short Ver.",
    title_id: "turn-heartbeats-into-tempo-sunna-solo-short-ver",
    source: "/musics/2.6--turn-heartbeats-into-tempo-sunna-solo-short-ver.mp3",
    duration: 119,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Turn Heartbeats Into Tempo with Chinese Vocal Short Ver.",
    title_id: "turn-heartbeats-into-tempo-with-chinese-vocal-short-ver",
    source:
      "/musics/2.6--turn-heartbeats-into-tempo-with-chinese-vocal-short-ver.mp3",
    duration: 153,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Turn Heartbeats Into Tempo with English Vocal Short Ver.",
    title_id: "turn-heartbeats-into-tempo-with-english-vocal-short-ver",
    source:
      "/musics/2.6--turn-heartbeats-into-tempo-with-english-vocal-short-ver.mp3",
    duration: 153,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Turn Heartbeats Into Tempo with Japanese Vocal Short Ver.",
    title_id: "turn-heartbeats-into-tempo-with-japanese-vocal-short-ver",
    source:
      "/musics/2.6--turn-heartbeats-into-tempo-with-japanese-vocal-short-ver.mp3",
    duration: 153,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Turn Heartbeats Into Tempo with Korean Vocal Short Ver.",
    title_id: "turn-heartbeats-into-tempo-with-korean-vocal-short-ver",
    source:
      "/musics/2.6--turn-heartbeats-into-tempo-with-korean-vocal-short-ver.mp3",
    duration: 153,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Uninvited Guest Theme",
    title_id: "uninvited-guest-theme",
    source: "/musics/2.6--uninvited-guest-theme.mp3",
    duration: 65,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Uproar of Old Dreams",
    title_id: "uproar-of-old-dreams",
    source: "/musics/2.6--uproar-of-old-dreams.mp3",
    duration: 117,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Vesper Boss Theme - Warm Night",
    title_id: "vesper-boss-theme-warm-night",
    source: "/musics/2.6--vesper-boss-theme-warm-night.mp3",
    duration: 307,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Vesper Boss Theme With Electric Guitar",
    title_id: "vesper-boss-theme-with-electric-guitar",
    source: "/musics/2.6--vesper-boss-theme-with-electric-guitar.mp3",
    duration: 343,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Warm Night",
    title_id: "warm-night",
    source: "/musics/2.6--warm-night.mp3",
    duration: 299,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
  {
    title: "Welcome to 404 Theme",
    title_id: "welcome-to-404-theme",
    source: "/musics/2.6--welcome-to-404-theme.mp3",
    duration: 54,
    created_at: new Date("2026-02-06"),
    ...Artists["2.6"],
    ...Albums["2.6"],
  },
];
