import { Track } from "@/types/track.type";
import { Albums } from "../albums";
import { Artists } from "../artists";

export const Album27Tracks: Track[] = [
  {
    title: "Black Wolf Romeul Boss Theme",
    title_id: "black-wolf-romeul-boss-theme",
    source: "/musics/2.7--black-wolf-romeul-boss-theme.mp3",
    duration: 355,
    created_at: new Date("2026-03-24"),
    ...Artists["2.7"],
    ...Albums["2.7"],
  },
  {
    title: "Champions Never Fall to the Past Teaser Theme",
    title_id: "champions-never-fall-to-the-past-teaser-theme",
    source: "/musics/2.7--champions-never-fall-to-the-past-teaser-theme.mp3",
    duration: 99,
    created_at: new Date("2026-03-24"),
    ...Artists["2.7"],
    ...Albums["2.7"],
  },
  {
    title: "Chronicle of Simmering Flavors Ending Theme",
    title_id: "chronicle-of-simmering-flavors-ending-theme",
    source: "/musics/2.7--chronicle-of-simmering-flavors-ending-theme.mp3",
    duration: 44,
    created_at: new Date("2026-03-24"),
    ...Artists["2.7"],
    ...Albums["2.7"],
  },
  {
    title: "Chronicle of Simmering Flavors Event Theme (Cooking)",
    title_id: "chronicle-of-simmering-flavors-event-theme-cooking",
    source:
      "/musics/2.7--chronicle-of-simmering-flavors-event-theme-cooking.mp3",
    duration: 177,
    created_at: new Date("2026-03-24"),
    ...Artists["2.7"],
    ...Albums["2.7"],
  },
  {
    title: "Chronicle of Simmering Flavors Event Theme (Ordering Ingredients)",
    title_id: "chronicle-of-simmering-flavors-event-theme-ordering-ingredients",
    source:
      "/musics/2.7--chronicle-of-simmering-flavors-event-theme-ordering-ingredients.mp3",
    duration: 220,
    created_at: new Date("2026-03-24"),
    ...Artists["2.7"],
    ...Albums["2.7"],
  },
  {
    title: "Cissia VS Promeia Theme",
    title_id: "cissia-vs-promeia-theme",
    source: "/musics/2.7--cissia-vs-promeia-theme.mp3",
    duration: 83,
    created_at: new Date("2026-03-24"),
    ...Artists["2.7"],
    ...Albums["2.7"],
  },
  {
    title: "Fantastical-Colored Heartbeat (CN Vocal Full Ver.)",
    title_id: "fantastical-colored-heartbeat-cn-vocal-full-ver",
    source: "/musics/2.7--fantastical-colored-heartbeat-cn-vocal-full-ver.mp3",
    duration: 276,
    created_at: new Date("2026-03-24"),
    ...Artists["2.7"],
    ...Albums["2.7"],
  },
  {
    title:
      "Fantastical-Colored Heartbeat (Instrumental Version) - Nangong Yu EP",
    title_id:
      "fantastical-colored-heartbeat-instrumental-version-nangong-yu-ep",
    source:
      "/musics/2.7--fantastical-colored-heartbeat-instrumental-version-nangong-yu-ep.mp3",
    duration: 276,
    created_at: new Date("2026-03-24"),
    ...Artists["2.7"],
    ...Albums["2.7"],
  },
  {
    title: "Fantastical-Colored Heartbeat (JP Vocal Full Ver.)",
    title_id: "fantastical-colored-heartbeat-jp-vocal-full-ver",
    source: "/musics/2.7--fantastical-colored-heartbeat-jp-vocal-full-ver.mp3",
    duration: 276,
    created_at: new Date("2026-03-24"),
    ...Artists["2.7"],
    ...Albums["2.7"],
  },
  {
    title: "Hollow Champion Battle Theme 1",
    title_id: "hollow-champion-battle-theme-1",
    source: "/musics/2.7--hollow-champion-battle-theme-1.mp3",
    duration: 256,
    created_at: new Date("2026-03-24"),
    ...Artists["2.7"],
    ...Albums["2.7"],
  },
  {
    title: "Hollow Champion Battle Theme 2",
    title_id: "hollow-champion-battle-theme-2",
    source: "/musics/2.7--hollow-champion-battle-theme-2.mp3",
    duration: 309,
    created_at: new Date("2026-03-24"),
    ...Artists["2.7"],
    ...Albums["2.7"],
  },
  {
    title: "Hollow Champion Venue Theme",
    title_id: "hollow-champion-venue-theme",
    source: "/musics/2.7--hollow-champion-venue-theme.mp3",
    duration: 225,
    created_at: new Date("2026-03-24"),
    ...Artists["2.7"],
    ...Albums["2.7"],
  },
  {
    title: "Ramiel Theme",
    title_id: "ramiel-theme",
    source: "/musics/2.7--ramiel-theme.mp3",
    duration: 137,
    created_at: new Date("2026-03-24"),
    ...Artists["2.7"],
    ...Albums["2.7"],
  },
  {
    title: "The Proxy and the Snake Theme",
    title_id: "the-proxy-and-the-snake-theme",
    source: "/musics/2.7--the-proxy-and-the-snake-theme.mp3",
    duration: 48,
    created_at: new Date("2026-03-24"),
    ...Artists["2.7"],
    ...Albums["2.7"],
  },
  {
    title: "Tiny Tech Whiz Theme (Marcel Group)",
    title_id: "tiny-tech-whiz-theme-marcel-group",
    source: "/musics/2.7--tiny-tech-whiz-theme-marcel-group.mp3",
    duration: 153,
    created_at: new Date("2026-03-24"),
    ...Artists["2.7"],
    ...Albums["2.7"],
  },
  {
    title: "Wings That Freeze Time Theme",
    title_id: "wings-that-freeze-time-theme",
    source: "/musics/2.7--wings-that-freeze-time-theme.mp3",
    duration: 67,
    created_at: new Date("2026-03-24"),
    ...Artists["2.7"],
    ...Albums["2.7"],
  },
  {
    title: "Within Sight Theme",
    title_id: "within-sight-theme",
    source: "/musics/2.7--within-sight-theme.mp3",
    duration: 17,
    created_at: new Date("2026-03-24"),
    ...Artists["2.7"],
    ...Albums["2.7"],
  },
];
