import { Track } from "@/types/track.type";
import { Albums } from "../albums";
import { Artists } from "../artists";

export const Album28Tracks: Track[] = [
  {
    title: "New: Eridan Sunset Teaser Theme",
    title_id: "new--eridan-sunset-teaser-theme",
    source: "/musics/2.8--new--eridan-sunset-teaser-theme.mp3",
    duration: 122,
    created_at: new Date("2026-05-06"),
    ...Artists["2.8"],
    ...Albums["2.8"],
  },
  {
    title: "A Close Call Theme",
    title_id: "a-close-call-theme-eridan-sunset",
    source: "/musics/2.8--a-close-call-theme-eridan-sunset.mp3",
    duration: 49,
    created_at: new Date("2026-05-06"),
    ...Artists["2.8"],
    ...Albums["2.8"],
  },
  {
    title: "Unknown Power Theme",
    title_id: "unknown-power-theme",
    source: "/musics/2.8--unknown-power-theme.mp3",
    duration: 72,
    created_at: new Date("2026-05-06"),
    ...Artists["2.8"],
    ...Albums["2.8"],
  },
  {
    title: "A First-Generation Void Hunter Theme",
    title_id: "a-first-generation-void-hunter-theme",
    source: "/musics/2.8--a-first-generation-void-hunter-theme.mp3",
    duration: 360,
    created_at: new Date("2026-05-06"),
    ...Artists["2.8"],
    ...Albums["2.8"],
  },
  {
    title: "Good Morning Roscaelifer Event Theme",
    title_id: "good-morning-roscaelifer-event-theme",
    source: "/musics/2.8--good-morning-roscaelifer-event-theme.mp3",
    duration: 192,
    created_at: new Date("2026-05-06"),
    ...Artists["2.8"],
    ...Albums["2.8"],
  },
  {
    title: "The Bangboo Job Board Event Theme",
    title_id: "the-bangboo-job-board-event-theme",
    source: "/musics/2.8--the-bangboo-job-board-event-theme.mp3",
    duration: 228,
    created_at: new Date("2026-05-06"),
    ...Artists["2.8"],
    ...Albums["2.8"],
  },
  {
    title: "Bootopia Event Theme Day - Exploration",
    title_id: "bootopia-event-theme-day--exploration",
    source: "/musics/2.8--bootopia-event-theme-day--exploration.mp3",
    duration: 346,
    created_at: new Date("2026-05-06"),
    ...Artists["2.8"],
    ...Albums["2.8"],
  },
  {
    title: "Bootopia Event Theme Night - Exploration",
    title_id: "bootopia-event-theme-night--exploration",
    source: "/musics/2.8--bootopia-event-theme-night--exploration.mp3",
    duration: 374,
    created_at: new Date("2026-05-06"),
    ...Artists["2.8"],
    ...Albums["2.8"],
  },
  {
    title: "Bootopia Event - Ferris Wheel Theme",
    title_id: "bootopia-event--ferris-wheel-theme",
    source: "/musics/2.8--bootopia-event--ferris-wheel-theme.mp3",
    duration: 187,
    created_at: new Date("2026-05-06"),
    ...Artists["2.8"],
    ...Albums["2.8"],
  },
  {
    title: "Bootopia Battle Theme 1",
    title_id: "bootopia-battle-theme-1",
    source: "/musics/2.8--bootopia-battle-theme-1.mp3",
    duration: 233,
    created_at: new Date("2026-05-06"),
    ...Artists["2.8"],
    ...Albums["2.8"],
  },
  {
    title: "Remielle Theme",
    title_id: "remielle-theme",
    source: "/musics/2.8--remielle-theme.mp3",
    duration: 307,
    created_at: new Date("2026-05-06"),
    ...Artists["2.8"],
    ...Albums["2.8"],
  },
  {
    title: "Remielle - Return to Rightful Owner Theme",
    title_id: "remielle--return-to-rightful-owner-theme",
    source: "/musics/2.8--remielle--return-to-rightful-owner-theme.mp3",
    duration: 70,
    created_at: new Date("2026-05-06"),
    ...Artists["2.8"],
    ...Albums["2.8"],
  },
  {
    title: "Promeia - Prey Predator Theme",
    title_id: "promeia--prey-predator-theme",
    source: "/musics/2.8--promeia--prey-predator-theme.mp3",
    duration: 32,
    created_at: new Date("2026-05-06"),
    ...Artists["2.8"],
    ...Albums["2.8"],
  },
  {
    title: "Starlight Billy Henshin Theme",
    title_id: "starlight-billy-henshin-theme",
    source: "/musics/2.8--starlight-billy-henshin-theme.mp3",
    duration: 56,
    created_at: new Date("2026-05-06"),
    ...Artists["2.8"],
    ...Albums["2.8"],
  },
  {
    title: "Starlight Billy EP - Billy Mode (English Lyrics)",
    title_id: "starlight-billy-ep--billy-mode-english-lyrics",
    source: "/musics/2.8--starlight-billy-ep--billy-mode-english-lyrics.mp3",
    duration: 190,
    created_at: new Date("2026-05-06"),
    ...Artists["2.8"],
    ...Albums["2.8"],
  },
  {
    title: "Starlight Billy EP - Billy Mode (Instrumental Ver.)",
    title_id: "starlight-billy-ep--billy-mode-instrumental-ver",
    source: "/musics/2.8--s-billy-ep--billy-mode-instrumental-ver.mp3",
    duration: 190,
    created_at: new Date("2026-05-06"),
    ...Artists["2.8"],
    ...Albums["2.8"],
  },
  {
    title: "Starlight - Billy Battle Theme",
    title_id: "starlight--billy-battle-theme",
    source: "/musics/2.8--starlight--billy-battle-theme.mp3",
    duration: 208,
    created_at: new Date("2026-05-06"),
    ...Artists["2.8"],
    ...Albums["2.8"],
  },
  {
    title: "Phaethon - The Wrong Dream Theme",
    title_id: "phaethon--the-wrong-dream-theme",
    source: "/musics/2.8--phaethon--the-wrong-dream-theme.mp3",
    duration: 17,
    created_at: new Date("2026-05-06"),
    ...Artists["2.8"],
    ...Albums["2.8"],
  },
  {
    title: "Phaethon Boss Theme Phase 1 - Terror Raptor Remix",
    title_id: "phaethon-boss-theme-phase-1--terror-raptor-remix",
    source: "/musics/2.8--phaethon-boss-theme-phase-1--terror-raptor-remix.mp3",
    duration: 381,
    created_at: new Date("2026-05-06"),
    ...Artists["2.8"],
    ...Albums["2.8"],
  },
  {
    title: "Phaethon of the Scorched Horizon Final Boss Theme",
    title_id: "phaethon-of-the-scorched-horizon-final-boss-theme",
    source:
      "/musics/2.8--phaethon-of-the-scorched-horizon-final-boss-theme.mp3",
    duration: 332,
    created_at: new Date("2026-05-06"),
    ...Artists["2.8"],
    ...Albums["2.8"],
  },
];
