import { Track } from "@/types/track.type";
import { Albums } from "../albums";
import { Artists } from "../artists";

export const Album30Tracks: Track[] = [
  {
    title: "Season 3 Teaser Theme - Before the Wind Rises",
    title_id: "season-3-teaser-theme--before-the-wind-rises",
    source: "/musics/3.0--season-3-teaser-theme--before-the-wind-rises.mp3",
    duration: 212,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "A Sleepwalker's Confession Teaser Theme",
    title_id: "a-sleepwalker-s-confession-teaser-theme",
    source: "/musics/3.0--a-sleepwalker-s-confession-teaser-theme.mp3",
    duration: 161,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Roscaelifer Intro Cutscene Theme",
    title_id: "roscaelifer-intro-cutscene-theme",
    source: "/musics/3.0--roscaelifer-intro-cutscene-theme.mp3",
    duration: 116,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Roscaelifer - Booastrum District Theme (Daytime)",
    title_id: "roscaelifer--booastrum-district-theme-daytime",
    source: "/musics/3.0--roscaelifer--booastrum-district-theme-daytime.mp3",
    duration: 258,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Roscaelifer - Booastrum District Theme (Nighttime)",
    title_id: "roscaelifer--booastrum-district-theme-nighttime",
    source: "/musics/3.0--roscaelifer--booastrum-district-theme-nighttime.mp3",
    duration: 251,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Roscaelifer - Booastrum District Theme (Rainy Day)",
    title_id: "roscaelifer--booastrum-district-theme-rainy-day",
    source: "/musics/3.0--roscaelifer--booastrum-district-theme-rainy-day.mp3",
    duration: 256,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Beckford Street Theme (Daytime)",
    title_id: "beckford-street-theme-daytime",
    source: "/musics/3.0--beckford-street-theme-daytime.mp3",
    duration: 258,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Beckford Street Theme (Nighttime)",
    title_id: "beckford-street-theme-nighttime",
    source: "/musics/3.0--beckford-street-theme-nighttime.mp3",
    duration: 251,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Emerald Central Park Theme (Daytime)",
    title_id: "emerald-central-park-theme-daytime",
    source: "/musics/3.0--emerald-central-park-theme-daytime.mp3",
    duration: 258,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Emerald Central Park Theme (Nighttime)",
    title_id: "emerald-central-park-theme-nighttime",
    source: "/musics/3.0--emerald-central-park-theme-nighttime.mp3",
    duration: 251,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Riding Hover Bus Theme",
    title_id: "riding-hover-bus-theme",
    source: "/musics/3.0--riding-hover-bus-theme.mp3",
    duration: 256,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Cuppa Moment Shop Theme",
    title_id: "cuppa-moment-shop-theme",
    source: "/musics/3.0--cuppa-moment-shop-theme.mp3",
    duration: 175,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Spotlight Theater Theme",
    title_id: "spotlight-theater-theme",
    source: "/musics/3.0--spotlight-theater-theme.mp3",
    duration: 160,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Amber Hall Theme",
    title_id: "amber-hall-theme",
    source: "/musics/3.0--amber-hall-theme.mp3",
    duration: 155,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "The Five Central Departments Theme",
    title_id: "the-five-central-departments-theme",
    source: "/musics/3.0--the-five-central-departments-theme.mp3",
    duration: 59,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "CCD Theme",
    title_id: "ccd-theme",
    source: "/musics/3.0--ccd-theme.mp3",
    duration: 328,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "CCD Exploration Theme",
    title_id: "ccd-exploration-theme",
    source: "/musics/3.0--ccd-exploration-theme.mp3",
    duration: 346,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "CCD Battle Theme",
    title_id: "ccd-battle-theme",
    source: "/musics/3.0--ccd-battle-theme.mp3",
    duration: 311,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Energy Hub Theme",
    title_id: "energy-hub-theme",
    source: "/musics/3.0--energy-hub-theme.mp3",
    duration: 223,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Energy Hub Battle Theme",
    title_id: "energy-hub-battle-theme",
    source: "/musics/3.0--energy-hub-battle-theme.mp3",
    duration: 187,
    created_at: new Date("2026-07-18"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Restricted Area - Energy Hub Exploration Theme",
    title_id: "restricted-area--energy-hub-exploration-theme",
    source: "/musics/3.0--restricted-area--energy-hub-exploration-theme.mp3",
    duration: 281,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Scamall Hollow Theme",
    title_id: "scamall-hollow-theme",
    source: "/musics/3.0--scamall-hollow-theme.mp3",
    duration: 224,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Scamall Hollow Theme (Vocal Variation)",
    title_id: "scamall-hollow-theme-vocal-variation",
    source: "/musics/3.0--scamall-hollow-theme-vocal-variation.mp3",
    duration: 226,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Sunken Corridor - Scamall Hollow Exploration Theme",
    title_id: "sunken-corridor--scamall-hollow-exploration-theme",
    source:
      "/musics/3.0--sunken-corridor--scamall-hollow-exploration-theme.mp3",
    duration: 256,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Scamall Hollow Battle Theme (Sick Cough Beat)",
    title_id: "scamall-hollow-battle-theme-sick-cough-beat",
    source: "/musics/3.0--scamall-hollow-battle-theme-sick-cough-beat.mp3",
    duration: 136,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Kabka Theme - The Mist of Dark Alleys",
    title_id: "kabka-theme--the-mist-of-dark-alleys",
    source: "/musics/3.0--kabka-theme--the-mist-of-dark-alleys.mp3",
    duration: 200,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Time to Play feat. Jazz One-Boo Band (True Blues)",
    title_id: "time-to-play-feat-jazz-one-boo-band-true-blues",
    source: "/musics/3.0--time-to-play-feat-jazz-one-boo-band-true-blues.mp3",
    duration: 131,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Tough Questions and Real Talk Theme",
    title_id: "tough-questions-and-real-talk-theme",
    source: "/musics/3.0--tough-questions-and-real-talk-theme.mp3",
    duration: 181,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Norma - Future Bangboo Lab Theme",
    title_id: "norma--future-bangboo-lab-theme",
    source: "/musics/3.0--norma--future-bangboo-lab-theme.mp3",
    duration: 227,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Norma Secret Operation Theme",
    title_id: "norma-secret-operation-theme",
    source: "/musics/3.0--norma-secret-operation-theme.mp3",
    duration: 166,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Stress Test Battle Theme (Norma Event)",
    title_id: "stress-test-battle-theme-norma-event",
    source: "/musics/3.0--stress-test-battle-theme-norma-event.mp3",
    duration: 126,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Data Domain Training Battle Theme (Norma Event)",
    title_id: "data-domain-training-battle-theme-norma-event",
    source: "/musics/3.0--data-domain-training-battle-theme-norma-event.mp3",
    duration: 126,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Norma Event Ending Theme - Because Tomorrow Still Comes",
    title_id: "norma-event-ending-theme--because-tomorrow-still-comes",
    source:
      "/musics/3.0--norma-event-ending-theme--because-tomorrow-still-comes.mp3",
    duration: 102,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Norma Theme - chaos.exe (Instrumental Ver.)",
    title_id: "norma-theme--chaos-exe-instrumental-ver",
    source: "/musics/3.0--norma-theme--chaos-exe-instrumental-ver.mp3",
    duration: 163,
    created_at: new Date("2026-07-18"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Norma EP - chaos.exe (With Lyrics)",
    title_id: "norma-ep--chaos-exe-with-lyrics",
    source: "/musics/3.0--norma-ep--chaos-exe-with-lyrics.mp3",
    duration: 163,
    created_at: new Date("2026-07-18"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Simulated Frontline Battle Theme (Mock Exam Comeback Plan Event)",
    title_id: "simulated-frontline-battle-theme-mock-exam-comeback-plan-event",
    source:
      "/musics/3.0--simulated-frontline-battle-theme-mock-exam-comeback-plan-event.mp3",
    duration: 142,
    created_at: new Date("2026-07-18"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Critical Showdown Battle Theme (Mock Exam Comeback Plan Event)",
    title_id: "critical-showdown-battle-theme-mock-exam-comeback-plan-event",
    source:
      "/musics/3.0--critical-showdown-battle-theme-mock-exam-comeback-plan-event.mp3",
    duration: 137,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Phaethon and Pyrois Cutscene Theme",
    title_id: "phaethon-and-pyrois-cutscene-theme",
    source: "/musics/3.0--phaethon-and-pyrois-cutscene-theme.mp3",
    duration: 157,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Infiltration and Allies Cutscene Theme",
    title_id: "infiltration-and-allies-cutscene-theme",
    source: "/musics/3.0--infiltration-and-allies-cutscene-theme.mp3",
    duration: 79,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Bashmu Cutscene Theme - Life or Death Escape",
    title_id: "bashmu-cutscene-theme--life-or-death-escape",
    source: "/musics/3.0--bashmu-cutscene-theme--life-or-death-escape.mp3",
    duration: 157,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Escape from Bashmu Theme",
    title_id: "escape-from-bashmu-theme",
    source: "/musics/3.0--escape-from-bashmu-theme.mp3",
    duration: 120,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Sunbringer Eldreda Dracaene Intro Cutscene Theme",
    title_id: "sunbringer-eldreda-dracaene-intro-cutscene-theme",
    source: "/musics/3.0--sunbringer-eldreda-dracaene-intro-cutscene-theme.mp3",
    duration: 36,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Girtablullu - Scorpion Ethereal Boss Theme",
    title_id: "girtablullu--scorpion-ethereal-boss-theme",
    source: "/musics/3.0--girtablullu--scorpion-ethereal-boss-theme.mp3",
    duration: 401,
    created_at: new Date("2026-06-17"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Prophecy - ZZZ 2nd Anniversary Song (With Lyrics)",
    title_id: "prophecy--zzz-2nd-anniversary-song-with-lyrics",
    source: "/musics/3.0--prophecy--zzz-2nd-anniversary-song-with-lyrics.mp3",
    duration: 254,
    created_at: new Date("2026-07-18"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Prophecy - ZZZ 2nd Anniversary (Instrumental Ver.)",
    title_id: "prophecy--zzz-2nd-anniversary-instrumental-ver",
    source: "/musics/3.0--prophecy--zzz-2nd-anniversary-instrumental-ver.mp3",
    duration: 247,
    created_at: new Date("2026-07-18"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Eh-ppy Birthday! (With Lyrics)",
    title_id: "eh-ppy-birthday-with-lyrics",
    source: "/musics/3.0--eh-ppy-birthday-with-lyrics.mp3",
    duration: 190,
    created_at: new Date("2026-07-18"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "2nd Anniversary Theme Song MV - \"Prophecy\"",
    title_id: "2nd-anniversary-theme-song-mv-prophecy",
    source: "/musics/3.0--2nd-anniversary-theme-song-mv-prophecy.mp3",
    duration: 142,
    created_at: new Date("2026-07-26"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Tiny Giant (Remix)",
    title_id: "tiny-giant-remix",
    source: "/musics/3.0--tiny-giant-remix.mp3",
    duration: 176,
    created_at: new Date("2026-07-26"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Phantom Blade Illusion",
    title_id: "phantom-blade-illusion",
    source: "/musics/3.0--phantom-blade-illusion.mp3",
    duration: 235,
    created_at: new Date("2026-07-27"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
  {
    title: "Remielle EP - \"Two to Tango\"",
    title_id: "remielle-ep-two-to-tango",
    source: "/musics/3.0--remielle-ep-two-to-tango.mp3",
    duration: 249,
    created_at: new Date("2026-07-27"),
    ...Artists["3.0"],
    ...Albums["3.0"],
  },
];
