import { Track } from "@/types/track.type";
import { Albums } from "../albums";
import { Artists } from "../artists";

export const Album31Tracks: Track[] = [
  {
    title: "Girtablullu (Stagnant Aberrant) Boss Theme - Evil and Instinct",
    title_id: "girtablullu-stagnant-aberrant-boss-theme--evil-and-instinct",
    source:
      "/musics/3.1--girtablullu-stagnant-aberrant-boss-theme--evil-and-instinct.mp3",
    duration: 228,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title: "Girtablullu - Stagnant Aberrant Boss Chase Theme (VS Remielle)",
    title_id: "girtablullu--stagnant-aberrant-boss-chase-theme-vs-remielle",
    source:
      "/musics/3.1--girtablullu--stagnant-aberrant-boss-chase-theme-vs-remielle.mp3",
    duration: 139,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title: "Girtablullu - Stagnant Aberrant Boss Theme (Story Ver.)",
    title_id: "girtablullu--stagnant-aberrant-boss-theme-story-ver",
    source: "/musics/3.1--girtablullu--stagnant-aberrant-boss-theme-story-ver.mp3",
    duration: 679,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title: "Girtablullu's Cocoon Theme",
    title_id: "girtablullu-s-cocoon-theme",
    source: "/musics/3.1--girtablullu-s-cocoon-theme.mp3",
    duration: 283,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title: "Roswick Hollow Battle Theme",
    title_id: "roswick-hollow-battle-theme",
    source: "/musics/3.1--roswick-hollow-battle-theme.mp3",
    duration: 137,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title: "The Long Goodbye Teaser Theme",
    title_id: "the-long-goodbye-teaser-theme",
    source: "/musics/3.1--the-long-goodbye-teaser-theme.mp3",
    duration: 163,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title: "The Long Goodbye Theme (Remielle)",
    title_id: "the-long-goodbye-theme-remielle",
    source: "/musics/3.1--the-long-goodbye-theme-remielle.mp3",
    duration: 118,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title: "Roswick Hollow Theme",
    title_id: "roswick-hollow-theme",
    source: "/musics/3.1--roswick-hollow-theme.mp3",
    duration: 159,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title: "Backflow Zone - Retroflux Zone Bottom Level Theme",
    title_id: "backflow-zone--retroflux-zone-bottom-level-theme",
    source:
      "/musics/3.1--backflow-zone--retroflux-zone-bottom-level-theme.mp3",
    duration: 188,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title: "Summer Festival Theme (Mix Ver.)",
    title_id: "summer-festival-theme-mix-ver",
    source: "/musics/3.1--summer-festival-theme-mix-ver.mp3",
    duration: 250,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title: "Backflow/Retroflux Zone Battle Theme",
    title_id: "backflow-retroflux-zone-battle-theme",
    source: "/musics/3.1--backflow-retroflux-zone-battle-theme.mp3",
    duration: 122,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title: "Roswick Hollow Theme (Variation)",
    title_id: "roswick-hollow-theme-variation",
    source: "/musics/3.1--roswick-hollow-theme-variation.mp3",
    duration: 195,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title: "Remielle Theme (Remielle's Hideout)",
    title_id: "remielle-theme-remielle-s-hideout",
    source: "/musics/3.1--remielle-theme-remielle-s-hideout.mp3",
    duration: 318,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title: "Two to Tango - Remielle EP (With Lyrics)",
    title_id: "remielle-ep--two-to-tango-with-lyrics",
    source: "/musics/3.1--remielle-ep--two-to-tango-with-lyrics.mp3",
    duration: 242,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title: "Remielle EP - Two to Tango (Instrumental Ver.)",
    title_id: "remielle-ep--two-to-tango-instrumental-ver",
    source: "/musics/3.1--remielle-ep--two-to-tango-instrumental-ver.mp3",
    duration: 244,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title: "Gear Street Theme (Daytime)",
    title_id: "gear-street-theme-daytime",
    source: "/musics/3.1--gear-street-theme-daytime.mp3",
    duration: 273,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title:
      "Discussion and OBJECTION!!! Theme (Guardboo's Trial - Eous'Infiltration)",
    title_id:
      "discussion-and-objection-theme-guardboo-s-trial--eous-infiltration",
    source:
      "/musics/3.1--discussion-and-objection-theme-guardboo-s-trial--eous-infiltration.mp3",
    duration: 110,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title: "Dancing With Remielle Theme (Banquet)",
    title_id: "dancing-with-remielle-theme-banquet",
    source: "/musics/3.1--dancing-with-remielle-theme-banquet.mp3",
    duration: 200,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title: "Roswick Hollow Exploration Theme",
    title_id: "roswick-hollow-exploration-theme",
    source: "/musics/3.1--roswick-hollow-exploration-theme.mp3",
    duration: 360,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title: "Gear Street Theme (Nighttime)",
    title_id: "gear-street-theme-nighttime",
    source: "/musics/3.1--gear-street-theme-nighttime.mp3",
    duration: 250,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title: "Backflow Zone Theme (Variation)",
    title_id: "backflow-zone-theme-variation",
    source: "/musics/3.1--backflow-zone-theme-variation.mp3",
    duration: 153,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title: "Backflow/Retroflux Zone Exploration Theme",
    title_id: "backflow-retroflux-zone-exploration-theme",
    source: "/musics/3.1--backflow-retroflux-zone-exploration-theme.mp3",
    duration: 360,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title: "Tea Party Surprise Theme",
    title_id: "tea-party-surprise-theme",
    source: "/musics/3.1--tea-party-surprise-theme.mp3",
    duration: 71,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title: "The Fall of Girtablullu Theme",
    title_id: "the-fall-of-girtablullu-theme",
    source: "/musics/3.1--the-fall-of-girtablullu-theme.mp3",
    duration: 91,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title: "Accomplice Act Theme",
    title_id: "accomplice-act-theme",
    source: "/musics/3.1--accomplice-act-theme.mp3",
    duration: 35,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
  {
    title: "Twisted Obsession Theme",
    title_id: "twisted-obsession-theme",
    source: "/musics/3.1--twisted-obsession-theme.mp3",
    duration: 29,
    created_at: new Date("2026-07-31"),
    ...Artists["3.1"],
    ...Albums["3.1"],
  },
];
