import { Track } from "@/types/track.type";
import { Albums } from "../albums";
import { Artists } from "../artists";

export const Album32Tracks: Track[] = [
  {
    title: "Kusarikku Boss Theme",
    title_id: "kusarikku-boss-theme",
    source: "/musics/3.2--kusarikku-boss-theme.mp3",
    duration: 378,
    created_at: new Date("2026-09-09"),
    ...Artists["3.2"],
    ...Albums["3.2"],
  },
  {
    title: "Vyrium District Theme",
    title_id: "vyrium-district-theme",
    source: "/musics/3.2--vyrium-district-theme.mp3",
    duration: 311,
    created_at: new Date("2026-09-09"),
    ...Artists["3.2"],
    ...Albums["3.2"],
  },
  {
    title: "Phaethon & Lindverne Theme (Resonance)",
    title_id: "phaethon-lindverne-theme-resonance",
    source: "/musics/3.2--phaethon-lindverne-theme-resonance.mp3",
    duration: 83,
    created_at: new Date("2026-09-09"),
    ...Artists["3.2"],
    ...Albums["3.2"],
  },
  {
    title: "Vyrium Restricted Area Battle Theme (Shrouded Reef Transfer Station)",
    title_id: "vyrium-restricted-area-battle-theme-shrouded-reef-transfer-station",
    source: "/musics/3.2--vyrium-restricted-area-battle-theme-shrouded-reef-transfer-station.mp3",
    duration: 168,
    created_at: new Date("2026-09-09"),
    ...Artists["3.2"],
    ...Albums["3.2"],
  },
  {
    title: "Link Up - Claret EP | Instrumental Version With English Lyrics",
    title_id: "link-up-claret-ep-instrumental-version-with-english-lyrics",
    source: "/musics/3.2--link-up-claret-ep-instrumental-version-with-english-lyrics.mp3",
    duration: 188,
    created_at: new Date("2026-09-09"),
    ...Artists["3.2"],
    ...Albums["3.2"],
  },
  {
    title: "Vyrium Restricted Area Battle Theme 1 (Porcelloy Research Institute)",
    title_id: "vyrium-restricted-area-battle-theme-1-porcelloy-research-institute",
    source: "/musics/3.2--vyrium-restricted-area-battle-theme-1-porcelloy-research-institute.mp3",
    duration: 168,
    created_at: new Date("2026-09-09"),
    ...Artists["3.2"],
    ...Albums["3.2"],
  },
  {
    title: "Kusarikku Boss Theme (Story Ver.)",
    title_id: "kusarikku-boss-theme-story-ver",
    source: "/musics/3.2--kusarikku-boss-theme-story-ver.mp3",
    duration: 328,
    created_at: new Date("2026-09-09"),
    ...Artists["3.2"],
    ...Albums["3.2"],
  },
  {
    title: "Mysterious Theme (Sunbringer's Secret)",
    title_id: "mysterious-theme-sunbringer-s-secret",
    source: "/musics/3.2--mysterious-theme-sunbringer-s-secret.mp3",
    duration: 184,
    created_at: new Date("2026-09-09"),
    ...Artists["3.2"],
    ...Albums["3.2"],
  },
  {
    title: "Vyrium Battle Theme 2 (Porcelloy Research Institute Undeground Area)",
    title_id: "vyrium-battle-theme-2-porcelloy-research-institute-undeground-area",
    source: "/musics/3.2--vyrium-battle-theme-2-porcelloy-research-institute-undeground-area.mp3",
    duration: 196,
    created_at: new Date("2026-09-09"),
    ...Artists["3.2"],
    ...Albums["3.2"],
  },
  {
    title: "Blazelight Hall Reception Room Theme",
    title_id: "blazelight-hall-reception-room-theme",
    source: "/musics/3.2--blazelight-hall-reception-room-theme.mp3",
    duration: 287,
    created_at: new Date("2026-09-09"),
    ...Artists["3.2"],
    ...Albums["3.2"],
  },
  {
    title: "Vyrium Restricted Area Full Theme (Porcelloy Research Institute)",
    title_id: "vyrium-restricted-area-full-theme-porcelloy-research-institute",
    source: "/musics/3.2--vyrium-restricted-area-full-theme-porcelloy-research-institute.mp3",
    duration: 409,
    created_at: new Date("2026-09-09"),
    ...Artists["3.2"],
    ...Albums["3.2"],
  },
  {
    title: "Vyrium Restricted Area Full Theme (Shrouded Reef Transfer Station)",
    title_id: "vyrium-restricted-area-full-theme-shrouded-reef-transfer-station",
    source: "/musics/3.2--vyrium-restricted-area-full-theme-shrouded-reef-transfer-station.mp3",
    duration: 168,
    created_at: new Date("2026-09-09"),
    ...Artists["3.2"],
    ...Albums["3.2"],
  },
  {
    title: "Link Up - Claret EP | Official English Lyrics",
    title_id: "link-up-claret-ep-official-english-lyrics",
    source: "/musics/3.2--link-up-claret-ep-official-english-lyrics.mp3",
    duration: 190,
    created_at: new Date("2026-09-09"),
    ...Artists["3.2"],
    ...Albums["3.2"],
  },
  {
    title: "Their Secret Histories Teaser Theme",
    title_id: "their-secret-histories-teaser-theme",
    source: "/musics/3.2--their-secret-histories-teaser-theme.mp3",
    duration: 115,
    created_at: new Date("2026-09-09"),
    ...Artists["3.2"],
    ...Albums["3.2"],
  },
  {
    title: "Phoenix Intro Theme (Unexpected Visitor)",
    title_id: "phoenix-intro-theme-unexpected-visitor",
    source: "/musics/3.2--phoenix-intro-theme-unexpected-visitor.mp3",
    duration: 58,
    created_at: new Date("2026-09-09"),
    ...Artists["3.2"],
    ...Albums["3.2"],
  },
  {
    title: "Claret Stealth Mode Theme (Transfer Station Infiltration)",
    title_id: "claret-stealth-mode-theme-transfer-station-infiltration",
    source: "/musics/3.2--claret-stealth-mode-theme-transfer-station-infiltration.mp3",
    duration: 253,
    created_at: new Date("2026-09-09"),
    ...Artists["3.2"],
    ...Albums["3.2"],
  },
  {
    title: "Claret Cutscene Theme (Unforgivable)",
    title_id: "claret-cutscene-theme-unforgivable",
    source: "/musics/3.2--claret-cutscene-theme-unforgivable.mp3",
    duration: 34,
    created_at: new Date("2026-09-09"),
    ...Artists["3.2"],
    ...Albums["3.2"],
  },
  {
    title: "Vyrium - Porcelloy Research Institute Exploration Theme",
    title_id: "vyrium-porcelloy-research-institute-exploration-theme",
    source: "/musics/3.2--vyrium-porcelloy-research-institute-exploration-theme.mp3",
    duration: 254,
    created_at: new Date("2026-09-09"),
    ...Artists["3.2"],
    ...Albums["3.2"],
  },
  {
    title: "Funny Theme (Heading to Vyrium)",
    title_id: "funny-theme-heading-to-vyrium",
    source: "/musics/3.2--funny-theme-heading-to-vyrium.mp3",
    duration: 179,
    created_at: new Date("2026-09-09"),
    ...Artists["3.2"],
    ...Albums["3.2"],
  },
  {
    title: "Vyrium - Shrouded Reef Transfer Station Exploration Theme",
    title_id: "vyrium-shrouded-reef-transfer-station-exploration-theme",
    source: "/musics/3.2--vyrium-shrouded-reef-transfer-station-exploration-theme.mp3",
    duration: 170,
    created_at: new Date("2026-09-09"),
    ...Artists["3.2"],
    ...Albums["3.2"],
  },
  {
    title: "Candidate Theme",
    title_id: "candidate-theme",
    source: "/musics/3.2--candidate-theme.mp3",
    duration: 51,
    created_at: new Date("2026-09-09"),
    ...Artists["3.2"],
    ...Albums["3.2"],
  },
  {
    title: "Pinball Knight Mission Mode Theme (Clink, Clank, Pinball Knight! Event)",
    title_id: "pinball-knight-mission-mode-theme-clink-clank-pinball-knight-event",
    source: "/musics/3.2--pinball-knight-mission-mode-theme-clink-clank-pinball-knight-event.mp3",
    duration: 174,
    created_at: new Date("2026-09-09"),
    ...Artists["3.2"],
    ...Albums["3.2"],
  },
  {
    title: "Pinball Knight Challenge Mode Theme (Clink, Clank, Pinball Knight! Event)",
    title_id: "pinball-knight-challenge-mode-theme-clink-clank-pinball-knight-event",
    source: "/musics/3.2--pinball-knight-challenge-mode-theme-clink-clank-pinball-knight-event.mp3",
    duration: 324,
    created_at: new Date("2026-09-09"),
    ...Artists["3.2"],
    ...Albums["3.2"],
  },
  {
    title: "Claret & Roxy Cutscene Theme (Secrets Behind Closed Doors)",
    title_id: "claret-roxy-cutscene-theme-secrets-behind-closed-doors",
    source: "/musics/3.2--claret-roxy-cutscene-theme-secrets-behind-closed-doors.mp3",
    duration: 36,
    created_at: new Date("2026-09-09"),
    ...Artists["3.2"],
    ...Albums["3.2"],
  },
];
